# Generated by Django 5.2.17 on 2026-10-06 11:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


GUARDS_SQL = """
ALTER TABLE macro_compilation_attempts ADD CONSTRAINT macro_compile_owner_scope_fk
    FOREIGN KEY (thesis_id, owner_id) REFERENCES macro_theses (id, owner_id)
    DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE macro_compilation_attempts ADD CONSTRAINT macro_compile_text_scope_fk
    FOREIGN KEY (thesis_id, text_version_id) REFERENCES macro_thesis_text_versions (thesis_id, id)
    DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE macro_thesis_interpretations ADD CONSTRAINT macro_interp_compile_text_fk
    FOREIGN KEY (thesis_id, text_version_id, compilation_id)
    REFERENCES macro_compilation_attempts (thesis_id, text_version_id, id)
    DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE macro_compilation_results ADD CONSTRAINT macro_compile_result_interp_fk
    FOREIGN KEY (attempt_id, interpretation_id)
    REFERENCES macro_thesis_interpretations (compilation_id, id)
    DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE macro_compilation_attempts ADD CONSTRAINT macro_compile_config_object
    CHECK (jsonb_typeof(configuration) = 'object');
ALTER TABLE macro_compilation_attempts ADD CONSTRAINT macro_compile_catalog_object
    CHECK (jsonb_typeof(model_metadata) = 'object');
ALTER TABLE macro_compilation_attempts ADD CONSTRAINT macro_compile_messages_array
    CHECK (jsonb_typeof(messages) = 'array');
ALTER TABLE macro_compilation_results ADD CONSTRAINT macro_compile_document_object
    CHECK (document IS NULL OR jsonb_typeof(document) = 'object');
ALTER TABLE macro_compilation_results ADD CONSTRAINT macro_compile_metadata_object
    CHECK (jsonb_typeof(provider_metadata) = 'object');
CREATE TRIGGER macro_compile_attempt_immutable BEFORE UPDATE OR DELETE ON macro_compilation_attempts
    FOR EACH ROW EXECUTE FUNCTION macro_thesis_reject_history_change();
CREATE TRIGGER macro_compile_result_immutable BEFORE UPDATE OR DELETE ON macro_compilation_results
    FOR EACH ROW EXECUTE FUNCTION macro_thesis_reject_history_change();
CREATE FUNCTION macro_compile_guard_result_time() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE admission macro_compilation_attempts%ROWTYPE;
BEGIN
    SELECT * INTO STRICT admission FROM macro_compilation_attempts WHERE id = NEW.attempt_id;
    IF NEW.finished_at < admission.created_at OR
        (NEW.status = 'compiled' AND NEW.finished_at >= admission.deadline_at) THEN
        RAISE EXCEPTION 'compilation result outside admitted time' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER macro_compile_result_time BEFORE INSERT ON macro_compilation_results
    FOR EACH ROW EXECUTE FUNCTION macro_compile_guard_result_time();
"""

REVERSE_SQL = """
DROP TRIGGER macro_compile_result_time ON macro_compilation_results;
DROP FUNCTION macro_compile_guard_result_time();
DROP TRIGGER macro_compile_result_immutable ON macro_compilation_results;
DROP TRIGGER macro_compile_attempt_immutable ON macro_compilation_attempts;
ALTER TABLE macro_compilation_results DROP CONSTRAINT macro_compile_metadata_object;
ALTER TABLE macro_compilation_results DROP CONSTRAINT macro_compile_document_object;
ALTER TABLE macro_compilation_attempts DROP CONSTRAINT macro_compile_messages_array;
ALTER TABLE macro_compilation_attempts DROP CONSTRAINT macro_compile_catalog_object;
ALTER TABLE macro_compilation_attempts DROP CONSTRAINT macro_compile_config_object;
ALTER TABLE macro_compilation_results DROP CONSTRAINT macro_compile_result_interp_fk;
ALTER TABLE macro_thesis_interpretations DROP CONSTRAINT macro_interp_compile_text_fk;
ALTER TABLE macro_compilation_attempts DROP CONSTRAINT macro_compile_text_scope_fk;
ALTER TABLE macro_compilation_attempts DROP CONSTRAINT macro_compile_owner_scope_fk;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('macro_theses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompilationAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command_id', models.UUIDField()),
                ('expected_revision', models.PositiveBigIntegerField()),
                ('request_digest', models.CharField(max_length=64)),
                ('provider', models.CharField(default='nanogpt', max_length=32)),
                ('model_id', models.CharField(max_length=255)),
                ('model_metadata', models.JSONField()),
                ('configuration', models.JSONField()),
                ('messages', models.JSONField()),
                ('prompt_digest', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField()),
                ('deadline_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'macro_compilation_attempts',
            },
        ),
        migrations.CreateModel(
            name='CompilationBudget',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'macro_compilation_budget',
            },
        ),
        migrations.RemoveConstraint(
            model_name='interpretationrecord',
            name='macro_interp_origin_manual',
        ),
        migrations.AlterField(
            model_name='interpretationrecord',
            name='origin',
            field=models.CharField(choices=[('user_supplied', 'user_supplied'), ('model_compilation', 'model_compilation')], default='user_supplied', editable=False, max_length=32),
        ),
        migrations.CreateModel(
            name='CompilationResult',
            fields=[
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='result', serialize=False, to='macro_theses.compilationattempt')),
                ('status', models.CharField(max_length=32)),
                ('stop_reason', models.CharField(max_length=64)),
                ('finished_at', models.DateTimeField()),
                ('document', models.JSONField(null=True)),
                ('provider_metadata', models.JSONField()),
            ],
            options={
                'db_table': 'macro_compilation_results',
            },
        ),
        migrations.AddField(
            model_name='compilationattempt',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compilationattempt',
            name='text_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='macro_theses.textversionrecord'),
        ),
        migrations.AddField(
            model_name='compilationattempt',
            name='thesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compilations', to='macro_theses.thesisrecord'),
        ),
        migrations.AddField(
            model_name='interpretationrecord',
            name='compilation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interpretations', to='macro_theses.compilationattempt'),
        ),
        migrations.AddConstraint(
            model_name='interpretationrecord',
            constraint=models.UniqueConstraint(fields=('compilation', 'id'), name='macro_interp_compilation_target'),
        ),
        migrations.AddConstraint(
            model_name='interpretationrecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('compilation__isnull', True), ('origin', 'user_supplied')), models.Q(('compilation__isnull', False), ('origin', 'model_compilation')), _connector='OR'), name='macro_interp_origin_provenance'),
        ),
        migrations.AddConstraint(
            model_name='compilationbudget',
            constraint=models.CheckConstraint(condition=models.Q(('id', 1)), name='macro_compile_budget_singleton'),
        ),
        migrations.AddField(
            model_name='compilationresult',
            name='interpretation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='macro_theses.interpretationrecord'),
        ),
        migrations.AddConstraint(
            model_name='compilationattempt',
            constraint=models.UniqueConstraint(fields=('owner', 'command_id'), name='macro_compile_command_identity'),
        ),
        migrations.AddConstraint(
            model_name='compilationattempt',
            constraint=models.UniqueConstraint(fields=('thesis', 'text_version', 'id'), name='macro_compile_text_target'),
        ),
        migrations.AddConstraint(
            model_name='compilationattempt',
            constraint=models.CheckConstraint(condition=models.Q(('expected_revision__gt', 0)), name='macro_compile_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='compilationattempt',
            constraint=models.CheckConstraint(condition=models.Q(('deadline_at__gt', models.F('created_at'))), name='macro_compile_time_order'),
        ),
        migrations.AddConstraint(
            model_name='compilationattempt',
            constraint=models.CheckConstraint(condition=models.Q(('request_digest__regex', '^[0-9a-f]{64}$')), name='macro_compile_digest'),
        ),
        migrations.AddConstraint(
            model_name='compilationattempt',
            constraint=models.CheckConstraint(condition=models.Q(('prompt_digest__regex', '^[0-9a-f]{64}$')), name='macro_compile_prompt_digest'),
        ),
        migrations.AddConstraint(
            model_name='compilationattempt',
            constraint=models.CheckConstraint(condition=models.Q(('provider__in', ('nanogpt', 'openrouter', 'cheaperinference'))), name='macro_compile_provider'),
        ),
        migrations.AddConstraint(
            model_name='compilationresult',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('compiled', 'stale', 'failed', 'outcome_unknown'))), name='macro_compile_status'),
        ),
        migrations.AddConstraint(
            model_name='compilationresult',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('document__isnull', False), ('interpretation__isnull', False), ('status', 'compiled')), models.Q(models.Q(('status', 'compiled'), _negated=True), ('interpretation__isnull', True)), _connector='OR'), name='macro_compile_result_provenance'),
        ),
        migrations.RunSQL(GUARDS_SQL, REVERSE_SQL),
    ]
