# Generated by Django 5.2.17 on 2026-10-09 11:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


GUARDS_SQL = """
ALTER TABLE macro_thesis_interpretations ADD CONSTRAINT macro_interp_card_object
    CHECK (review_card IS NULL OR (origin = 'model_compilation' AND jsonb_typeof(review_card) = 'object'));
ALTER TABLE macro_refinement_submissions ADD CONSTRAINT macro_refine_owner_scope_fk
    FOREIGN KEY (thesis_id, owner_id) REFERENCES macro_theses (id, owner_id)
    DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE macro_refinement_submissions ADD CONSTRAINT macro_refine_parent_scope_fk
    FOREIGN KEY (thesis_id, text_version_id, parent_attempt_id)
    REFERENCES macro_compilation_attempts (thesis_id, text_version_id, id)
    DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE macro_compilation_attempts ADD CONSTRAINT macro_compile_refine_scope_fk
    FOREIGN KEY (thesis_id, text_version_id, refinement_id)
    REFERENCES macro_refinement_submissions (thesis_id, text_version_id, id)
    DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE macro_refinement_submissions ADD CONSTRAINT macro_refine_answers_array
    CHECK (CASE WHEN jsonb_typeof(answers) = 'array'
           THEN jsonb_array_length(answers) BETWEEN 1 AND 16 ELSE FALSE END);
ALTER TABLE macro_refinement_submissions ADD CONSTRAINT macro_refine_inputs_array
    CHECK (CASE WHEN jsonb_typeof(cumulative_inputs) = 'array'
           THEN jsonb_array_length(cumulative_inputs) BETWEEN 1 AND 16 ELSE FALSE END);
CREATE TRIGGER macro_refine_immutable BEFORE UPDATE OR DELETE ON macro_refinement_submissions
    FOR EACH ROW EXECUTE FUNCTION macro_thesis_reject_history_change();

CREATE FUNCTION macro_refine_guard_parent() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE parent macro_compilation_attempts%ROWTYPE;
DECLARE completed macro_compilation_results%ROWTYPE;
DECLARE prior jsonb := '[]'::jsonb;
DECLARE prior_count integer;
DECLARE i integer;
BEGIN
    SELECT * INTO STRICT parent FROM macro_compilation_attempts WHERE id = NEW.parent_attempt_id;
    SELECT * INTO STRICT completed FROM macro_compilation_results WHERE attempt_id = parent.id;
    IF completed.status <> 'compiled' OR NEW.created_at < completed.finished_at
       OR NEW.expected_revision <= parent.expected_revision THEN
        RAISE EXCEPTION 'refinement requires an available completed parent' USING ERRCODE = '23514';
    END IF;
    IF parent.refinement_id IS NOT NULL THEN
        SELECT cumulative_inputs INTO STRICT prior FROM macro_refinement_submissions
            WHERE id = parent.refinement_id;
    END IF;
    prior_count := jsonb_array_length(prior);
    IF jsonb_typeof(NEW.answers) <> 'array' OR jsonb_typeof(NEW.cumulative_inputs) <> 'array'
       OR jsonb_array_length(NEW.cumulative_inputs) <> prior_count + jsonb_array_length(NEW.answers) THEN
        RAISE EXCEPTION 'refinement must retain its exact answer history' USING ERRCODE = '23514';
    END IF;
    IF prior_count > 0 THEN
        FOR i IN 0..prior_count - 1 LOOP
            IF NEW.cumulative_inputs -> i IS DISTINCT FROM prior -> i THEN
                RAISE EXCEPTION 'refinement cannot replace earlier answers' USING ERRCODE = '23514';
            END IF;
        END LOOP;
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER macro_refine_parent BEFORE INSERT ON macro_refinement_submissions
    FOR EACH ROW EXECUTE FUNCTION macro_refine_guard_parent();

CREATE FUNCTION macro_compile_guard_refinement_time() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE available_at timestamptz;
BEGIN
    IF NEW.refinement_id IS NOT NULL THEN
        SELECT created_at INTO STRICT available_at FROM macro_refinement_submissions
            WHERE id = NEW.refinement_id;
        IF NEW.created_at < available_at THEN
            RAISE EXCEPTION 'compilation cannot precede saved answers' USING ERRCODE = '23514';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER macro_compile_refinement_time BEFORE INSERT ON macro_compilation_attempts
    FOR EACH ROW EXECUTE FUNCTION macro_compile_guard_refinement_time();
"""

REVERSE_SQL = """
DROP TRIGGER macro_compile_refinement_time ON macro_compilation_attempts;
DROP FUNCTION macro_compile_guard_refinement_time();
DROP TRIGGER macro_refine_parent ON macro_refinement_submissions;
DROP FUNCTION macro_refine_guard_parent();
DROP TRIGGER macro_refine_immutable ON macro_refinement_submissions;
ALTER TABLE macro_refinement_submissions DROP CONSTRAINT macro_refine_inputs_array;
ALTER TABLE macro_refinement_submissions DROP CONSTRAINT macro_refine_answers_array;
ALTER TABLE macro_compilation_attempts DROP CONSTRAINT macro_compile_refine_scope_fk;
ALTER TABLE macro_refinement_submissions DROP CONSTRAINT macro_refine_parent_scope_fk;
ALTER TABLE macro_refinement_submissions DROP CONSTRAINT macro_refine_owner_scope_fk;
ALTER TABLE macro_thesis_interpretations DROP CONSTRAINT macro_interp_card_object;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('macro_theses', '0002_model_compilation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interpretationrecord',
            name='review_card',
            field=models.JSONField(null=True),
        ),
        migrations.CreateModel(
            name='RefinementSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command_id', models.UUIDField()),
                ('expected_revision', models.PositiveBigIntegerField()),
                ('request_digest', models.CharField(max_length=64)),
                ('answers', models.JSONField()),
                ('cumulative_inputs', models.JSONField()),
                ('created_at', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('parent_attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refinement_submissions', to='macro_theses.compilationattempt')),
                ('text_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='macro_theses.textversionrecord')),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refinements', to='macro_theses.thesisrecord')),
            ],
            options={
                'db_table': 'macro_refinement_submissions',
            },
        ),
        migrations.AddField(
            model_name='compilationattempt',
            name='refinement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compilations', to='macro_theses.refinementsubmission'),
        ),
        migrations.AddConstraint(
            model_name='refinementsubmission',
            constraint=models.UniqueConstraint(fields=('owner', 'command_id'), name='macro_refine_command_identity'),
        ),
        migrations.AddConstraint(
            model_name='refinementsubmission',
            constraint=models.UniqueConstraint(fields=('thesis', 'text_version', 'id'), name='macro_refine_text_target'),
        ),
        migrations.AddConstraint(
            model_name='refinementsubmission',
            constraint=models.CheckConstraint(condition=models.Q(('expected_revision__gt', 0)), name='macro_refine_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='refinementsubmission',
            constraint=models.CheckConstraint(condition=models.Q(('request_digest__regex', '^[0-9a-f]{64}$')), name='macro_refine_request_digest'),
        ),
        migrations.RunSQL(GUARDS_SQL, REVERSE_SQL),
    ]
