# Generated by Django 5.2.17 on 2026-10-09 21:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('macro_theses', '0003_review_card_refinement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('capture', 'capture'), ('analysis', 'analysis'), ('daily_review', 'daily_review')], max_length=16)),
                ('command_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('identity_key', models.CharField(max_length=128)),
                ('intended_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('local_date', models.DateField(null=True)),
                ('period_start', models.DateTimeField(null=True)),
                ('cutoff', models.DateTimeField(null=True)),
                ('late', models.BooleanField()),
                ('coalesced_intervals', models.PositiveBigIntegerField(default=0)),
                ('state', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('completed', 'completed'), ('blocked', 'blocked')], default='pending', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('active_token', models.UUIDField(null=True)),
                ('lease_until', models.DateTimeField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='macro_theses.thesisrecord')),
            ],
        ),
        migrations.CreateModel(
            name='SlotLease',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('admitted_at', models.DateTimeField()),
                ('deadline_at', models.DateTimeField()),
                ('mode', models.CharField(choices=[('execute', 'execute'), ('recover', 'recover')], max_length=8)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='macro_scheduling.scheduledslot')),
            ],
        ),
        migrations.CreateModel(
            name='WatchRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveBigIntegerField(default=0)),
                ('changed_at', models.DateTimeField()),
                ('next_capture_at', models.DateTimeField()),
                ('next_analysis_at', models.DateTimeField()),
                ('next_daily_date', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='macro_theses.thesisrecord')),
            ],
        ),
        migrations.AddField(
            model_name='scheduledslot',
            name='watch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='macro_scheduling.watchrecord'),
        ),
        migrations.CreateModel(
            name='WatchVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command_id', models.UUIDField()),
                ('sequence', models.PositiveBigIntegerField()),
                ('configuration', models.JSONField()),
                ('configuration_digest', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='macro_scheduling.watchrecord')),
            ],
        ),
        migrations.AddField(
            model_name='watchrecord',
            name='current_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_watches', to='macro_scheduling.watchversion'),
        ),
        migrations.AddField(
            model_name='scheduledslot',
            name='watch_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='macro_scheduling.watchversion'),
        ),
        migrations.CreateModel(
            name='AnalysisDispatch',
            fields=[
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='macro_scheduling.scheduledslot')),
                ('request', models.JSONField()),
                ('request_digest', models.CharField(max_length=64)),
                ('started_at', models.DateTimeField()),
                ('lease', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='macro_scheduling.slotlease')),
            ],
        ),
        migrations.CreateModel(
            name='SlotOutcome',
            fields=[
                ('lease', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='macro_scheduling.slotlease')),
                ('status', models.CharField(choices=[('completed', 'completed'), ('failed', 'failed'), ('unresolved', 'unresolved'), ('blocked', 'blocked'), ('expired', 'expired')], max_length=16)),
                ('payload', models.JSONField()),
                ('finished_at', models.DateTimeField()),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ('completed', 'failed', 'unresolved', 'blocked', 'expired'))), name='schedule_outcome_status')],
            },
        ),
        migrations.AddConstraint(
            model_name='slotlease',
            constraint=models.UniqueConstraint(fields=('slot', 'sequence'), name='schedule_lease_sequence'),
        ),
        migrations.AddConstraint(
            model_name='slotlease',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gt', 0)), name='schedule_lease_positive'),
        ),
        migrations.AddConstraint(
            model_name='slotlease',
            constraint=models.CheckConstraint(condition=models.Q(('deadline_at__gt', models.F('admitted_at'))), name='schedule_lease_deadline'),
        ),
        migrations.AddConstraint(
            model_name='slotlease',
            constraint=models.CheckConstraint(condition=models.Q(('mode__in', ('execute', 'recover'))), name='schedule_lease_mode'),
        ),
        migrations.AddConstraint(
            model_name='watchversion',
            constraint=models.UniqueConstraint(fields=('owner', 'command_id'), name='schedule_config_command'),
        ),
        migrations.AddConstraint(
            model_name='watchversion',
            constraint=models.UniqueConstraint(fields=('watch', 'sequence'), name='schedule_version_sequence'),
        ),
        migrations.AddConstraint(
            model_name='watchversion',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gt', 0)), name='schedule_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='watchversion',
            constraint=models.CheckConstraint(condition=models.Q(('configuration_digest__regex', '^[0-9a-f]{64}$')), name='schedule_config_digest'),
        ),
        migrations.AddConstraint(
            model_name='watchrecord',
            constraint=models.UniqueConstraint(fields=('owner', 'thesis'), name='schedule_owner_thesis'),
        ),
        migrations.AddConstraint(
            model_name='scheduledslot',
            constraint=models.UniqueConstraint(fields=('owner', 'thesis', 'kind', 'identity_key'), name='schedule_slot_identity'),
        ),
        migrations.AddConstraint(
            model_name='scheduledslot',
            constraint=models.UniqueConstraint(fields=('owner', 'thesis', 'kind', 'local_date'), name='schedule_daily_identity'),
        ),
        migrations.AddConstraint(
            model_name='scheduledslot',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ('capture', 'analysis', 'daily_review'))), name='schedule_slot_kind'),
        ),
        migrations.AddConstraint(
            model_name='scheduledslot',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ('pending', 'running', 'completed', 'blocked'))), name='schedule_slot_state'),
        ),
        migrations.AddConstraint(
            model_name='scheduledslot',
            constraint=models.CheckConstraint(condition=models.Q(('created_at__gte', models.F('intended_at'))), name='schedule_due_creation'),
        ),
        migrations.AddConstraint(
            model_name='scheduledslot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('coalesced_intervals', 0), ('cutoff', models.F('intended_at')), ('cutoff__gt', models.F('period_start')), ('cutoff__isnull', False), ('kind', 'daily_review'), ('local_date__isnull', False), ('period_start__isnull', False)), models.Q(models.Q(('kind', 'daily_review'), _negated=True), ('cutoff__isnull', True), ('local_date__isnull', True), ('period_start__isnull', True)), _connector='OR'), name='schedule_daily_interval'),
        ),
        migrations.AddConstraint(
            model_name='scheduledslot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active_token__isnull', False), ('lease_until__isnull', False), ('state', 'running')), models.Q(models.Q(('state', 'running'), _negated=True), ('active_token__isnull', True), ('lease_until__isnull', True)), _connector='OR'), name='schedule_active_lease'),
        ),
        migrations.AddConstraint(
            model_name='analysisdispatch',
            constraint=models.CheckConstraint(condition=models.Q(('request_digest__regex', '^[0-9a-f]{64}$')), name='schedule_dispatch_digest'),
        ),
    ]
