# Generated by Django 5.2.17 on 2026-10-09 21:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macro_scheduling', '0001_initial'),
        ('macro_theses', '0003_review_card_refinement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='scheduledslot',
            index=models.Index(fields=['owner', 'kind', 'intended_at'], name='schedule_due_owner_kind'),
        ),
        migrations.AddIndex(
            model_name='scheduledslot',
            index=models.Index(fields=['watch', 'kind', 'state'], name='schedule_watch_kind_state'),
        ),
    ]
