# Generated by Django 5.2.17 on 2026-10-10 11:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


# Preserve original outcomes; only an audited exact new lease can reopen blocked work.
SQL = """
CREATE OR REPLACE FUNCTION schedule_insert_guard() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE w macro_scheduling_watchrecord; s macro_scheduling_scheduledslot;
 v macro_scheduling_watchversion; l macro_scheduling_slotlease; p macro_scheduling_slotlease;
 r macro_scheduling_slotrecovery; saved_outcome macro_scheduling_slotoutcome;
 old_configuration jsonb; expected_owner uuid;
BEGIN
 IF TG_TABLE_NAME = 'macro_scheduling_watchrecord' THEN
  SELECT owner_id INTO expected_owner FROM macro_theses WHERE id = NEW.thesis_id;
  IF NEW.owner_id IS DISTINCT FROM expected_owner OR NEW.revision <> 0 OR NEW.current_version_id IS NOT NULL THEN
   RAISE EXCEPTION 'watch must begin in its owner thesis scope' USING ERRCODE = '23514';
  END IF;
 ELSIF TG_TABLE_NAME = 'macro_scheduling_watchversion' THEN
  SELECT * INTO w FROM macro_scheduling_watchrecord WHERE id = NEW.watch_id;
  IF NEW.owner_id IS DISTINCT FROM w.owner_id OR NEW.sequence <> w.revision + 1
   OR NEW.created_at < w.changed_at OR jsonb_typeof(NEW.configuration) <> 'object'
   OR NEW.configuration->>'schema_version' IS DISTINCT FROM 'internal-desk-watch-v1' THEN
   RAISE EXCEPTION 'watch version scope/time/configuration mismatch' USING ERRCODE = '23514';
  END IF;
 ELSIF TG_TABLE_NAME = 'macro_scheduling_scheduledslot' THEN
  SELECT * INTO w FROM macro_scheduling_watchrecord WHERE id = NEW.watch_id;
  SELECT * INTO v FROM macro_scheduling_watchversion WHERE id = NEW.watch_version_id;
  IF NEW.owner_id IS DISTINCT FROM w.owner_id OR NEW.thesis_id IS DISTINCT FROM w.thesis_id
   OR v.watch_id IS DISTINCT FROM w.id OR NEW.watch_version_id IS DISTINCT FROM w.current_version_id
   OR NEW.created_at < w.changed_at OR NEW.state <> 'pending' OR NEW.attempt_count <> 0
   OR NEW.active_token IS NOT NULL OR NEW.lease_until IS NOT NULL
   OR NEW.late IS DISTINCT FROM (NEW.created_at > NEW.intended_at)
   OR (NEW.kind = 'daily_review' AND NEW.identity_key <> 'daily_review:' || NEW.local_date::text) THEN
   RAISE EXCEPTION 'slot must begin pending with exact watch scope and honest lateness' USING ERRCODE = '23514';
  END IF;
 ELSIF TG_TABLE_NAME = 'macro_scheduling_slotrecovery' THEN
  SELECT * INTO s FROM macro_scheduling_scheduledslot WHERE id = NEW.slot_id;
  SELECT * INTO w FROM macro_scheduling_watchrecord WHERE id = s.watch_id;
  SELECT * INTO v FROM macro_scheduling_watchversion WHERE id = NEW.watch_version_id;
  SELECT * INTO p FROM macro_scheduling_slotlease WHERE token = NEW.prior_lease_id;
  SELECT * INTO saved_outcome FROM macro_scheduling_slotoutcome WHERE lease_id = p.token;
  SELECT configuration INTO old_configuration FROM macro_scheduling_watchversion WHERE id = s.watch_version_id;
  IF NEW.owner_id IS DISTINCT FROM s.owner_id OR s.state IS DISTINCT FROM 'blocked'
   OR p.slot_id IS DISTINCT FROM s.id OR p.sequence IS DISTINCT FROM s.attempt_count
   OR saved_outcome.status IS NULL OR saved_outcome.status NOT IN ('failed', 'unresolved', 'blocked')
   OR v.watch_id IS DISTINCT FROM w.id OR v.owner_id IS DISTINCT FROM s.owner_id
   OR NEW.watch_version_id IS DISTINCT FROM w.current_version_id
   OR NEW.created_at < w.changed_at OR NEW.created_at < saved_outcome.finished_at
   OR NEW.reason !~ '[^[:space:]]' OR length(NEW.reason) > 2000
   OR EXISTS (SELECT 1 FROM macro_scheduling_slotlease WHERE token = NEW.initial_lease_token)
   OR (NEW.action = 'retry' AND EXISTS (SELECT 1 FROM macro_scheduling_analysisdispatch WHERE slot_id = s.id))
   OR (NEW.action = 'reconcile' AND (s.kind <> 'analysis' OR NOT EXISTS
       (SELECT 1 FROM macro_scheduling_analysisdispatch WHERE slot_id = s.id)))
   OR (s.kind = 'daily_review' AND v.configuration->'sources' IS DISTINCT FROM old_configuration->'sources') THEN
   RAISE EXCEPTION 'recovery must bind its latest blocked outcome and reviewed watch scope' USING ERRCODE = '23514';
  END IF;
 ELSIF TG_TABLE_NAME = 'macro_scheduling_slotlease' THEN
  SELECT * INTO s FROM macro_scheduling_scheduledslot WHERE id = NEW.slot_id;
  SELECT * INTO p FROM macro_scheduling_slotlease WHERE token = s.active_token;
  IF NEW.recovery_id IS NULL THEN
   SELECT * INTO v FROM macro_scheduling_watchversion WHERE id = s.watch_version_id;
   IF s.state NOT IN ('pending', 'running') OR (s.state = 'running' AND p.recovery_id IS NOT NULL) THEN
    RAISE EXCEPTION 'ordinary lease cannot clear or discard manual recovery' USING ERRCODE = '23514';
   END IF;
  ELSE
   SELECT * INTO r FROM macro_scheduling_slotrecovery WHERE id = NEW.recovery_id;
   SELECT * INTO v FROM macro_scheduling_watchversion WHERE id = r.watch_version_id;
   IF r.slot_id IS DISTINCT FROM s.id OR r.owner_id IS DISTINCT FROM s.owner_id
    OR NEW.admitted_at < r.created_at OR s.state NOT IN ('blocked', 'running') THEN
    RAISE EXCEPTION 'lease recovery scope/time mismatch' USING ERRCODE = '23514';
   END IF;
   IF s.state = 'blocked' THEN
    SELECT * INTO l FROM macro_scheduling_slotlease WHERE token = r.prior_lease_id;
    IF NEW.token IS DISTINCT FROM r.initial_lease_token OR NEW.admitted_at IS DISTINCT FROM r.created_at
     OR l.slot_id IS DISTINCT FROM s.id OR l.sequence IS DISTINCT FROM s.attempt_count THEN
     RAISE EXCEPTION 'blocked work requires the exact initial audited recovery lease' USING ERRCODE = '23514';
    END IF;
   ELSIF p.recovery_id IS DISTINCT FROM NEW.recovery_id THEN
    RAISE EXCEPTION 'expired recovery lease must carry its reviewed execution version' USING ERRCODE = '23514';
   END IF;
  END IF;
  IF NEW.sequence <> s.attempt_count + 1 OR NEW.admitted_at < s.created_at
   OR NEW.deadline_at IS DISTINCT FROM NEW.admitted_at + (v.configuration->>'lease_seconds')::integer * interval '1 second'
   OR (NEW.mode = 'recover') IS DISTINCT FROM EXISTS (SELECT 1 FROM macro_scheduling_analysisdispatch WHERE slot_id = s.id) THEN
   RAISE EXCEPTION 'lease scope/time/mode mismatch' USING ERRCODE = '23514';
  END IF;
  IF s.state = 'running' AND (s.lease_until > NEW.admitted_at OR NOT EXISTS
    (SELECT 1 FROM macro_scheduling_slotoutcome WHERE lease_id = s.active_token AND status = 'expired')) THEN
   RAISE EXCEPTION 'live lease cannot be replaced without expired outcome' USING ERRCODE = '23514';
  END IF;
 ELSIF TG_TABLE_NAME = 'macro_scheduling_slotoutcome' THEN
  SELECT * INTO l FROM macro_scheduling_slotlease WHERE token = NEW.lease_id;
  SELECT * INTO s FROM macro_scheduling_scheduledslot WHERE id = l.slot_id;
  IF s.state <> 'running' OR s.active_token IS DISTINCT FROM l.token OR NEW.finished_at < l.admitted_at
   OR jsonb_typeof(NEW.payload) <> 'object'
   OR (NEW.status = 'expired' AND NEW.finished_at < l.deadline_at)
   OR (NEW.status <> 'expired' AND NEW.finished_at >= l.deadline_at) THEN
   RAISE EXCEPTION 'outcome must preserve the protected active lease ordering' USING ERRCODE = '23514';
  END IF;
 ELSIF TG_TABLE_NAME = 'macro_scheduling_analysisdispatch' THEN
  SELECT * INTO s FROM macro_scheduling_scheduledslot WHERE id = NEW.slot_id;
  SELECT * INTO l FROM macro_scheduling_slotlease WHERE token = NEW.lease_id;
  IF l.recovery_id IS NULL THEN
   SELECT * INTO v FROM macro_scheduling_watchversion WHERE id = s.watch_version_id;
  ELSE
   SELECT * INTO r FROM macro_scheduling_slotrecovery WHERE id = l.recovery_id;
   SELECT * INTO v FROM macro_scheduling_watchversion WHERE id = r.watch_version_id;
  END IF;
  IF s.kind <> 'analysis' OR s.state <> 'running' OR s.active_token IS DISTINCT FROM l.token
   OR l.slot_id IS DISTINCT FROM s.id OR l.mode <> 'execute'
   OR NEW.started_at < l.admitted_at OR NEW.started_at >= l.deadline_at
   OR jsonb_typeof(NEW.request) <> 'object'
   OR NEW.request->>'expected_approval_id' IS DISTINCT FROM v.configuration->>'approval_id'
   OR NEW.request->>'expected_exposure_digest' IS DISTINCT FROM v.configuration->>'exposure_digest'
   OR NEW.request->>'provider' IS DISTINCT FROM v.configuration->>'provider'
   OR NEW.request->>'model_id' IS DISTINCT FROM v.configuration->>'model_id'
   OR NEW.request->'model_configuration' IS DISTINCT FROM v.configuration->'model_configuration'
   OR NOT EXISTS (SELECT 1 FROM jsonb_array_elements(v.configuration->'sources') source
      WHERE source->>'source_id' = NEW.request->>'source_id') THEN
   RAISE EXCEPTION 'analysis dispatch must bind its exact active lease and configured request' USING ERRCODE = '23514';
  END IF;
 END IF;
 RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION schedule_state_guard() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE v macro_scheduling_watchversion; l macro_scheduling_slotlease;
 r macro_scheduling_slotrecovery; p macro_scheduling_slotlease; outcome varchar;
BEGIN
 IF TG_TABLE_NAME = 'macro_scheduling_watchrecord' THEN
  SELECT * INTO v FROM macro_scheduling_watchversion WHERE id = NEW.current_version_id;
  IF NEW.id <> OLD.id OR NEW.owner_id <> OLD.owner_id OR NEW.thesis_id <> OLD.thesis_id
   OR NEW.changed_at < OLD.changed_at OR NEW.next_capture_at < OLD.next_capture_at
   OR NEW.next_analysis_at < OLD.next_analysis_at OR NEW.next_daily_date < OLD.next_daily_date
   OR NEW.revision < OLD.revision OR NEW.revision > OLD.revision + 1
   OR v.watch_id IS DISTINCT FROM NEW.id OR v.sequence IS DISTINCT FROM NEW.revision
   OR (NEW.revision = OLD.revision AND NEW.current_version_id IS DISTINCT FROM OLD.current_version_id)
   OR (NEW.revision = OLD.revision + 1 AND (NEW.current_version_id IS NOT DISTINCT FROM OLD.current_version_id
       OR v.created_at IS DISTINCT FROM NEW.changed_at)) THEN
   RAISE EXCEPTION 'invalid watch state or cursor transition' USING ERRCODE = '23514';
  END IF;
 ELSIF TG_TABLE_NAME = 'macro_scheduling_scheduledslot' THEN
  IF (to_jsonb(NEW) - ARRAY['state','attempt_count','active_token','lease_until']) IS DISTINCT FROM
     (to_jsonb(OLD) - ARRAY['state','attempt_count','active_token','lease_until'])
   OR OLD.state = 'completed' OR (OLD.state = 'blocked' AND NEW.state <> 'running') THEN
   RAISE EXCEPTION 'slot identity/input and terminal state are immutable' USING ERRCODE = '23514';
  END IF;
  IF NEW.state = 'running' THEN
   SELECT * INTO l FROM macro_scheduling_slotlease WHERE token = NEW.active_token;
   IF l.slot_id IS DISTINCT FROM NEW.id OR l.sequence IS DISTINCT FROM NEW.attempt_count
    OR l.deadline_at IS DISTINCT FROM NEW.lease_until OR NEW.attempt_count <> OLD.attempt_count + 1 THEN
    RAISE EXCEPTION 'slot running state requires its exact new lease' USING ERRCODE = '23514';
   END IF;
   IF OLD.state = 'blocked' THEN
    SELECT * INTO r FROM macro_scheduling_slotrecovery WHERE id = l.recovery_id;
    SELECT * INTO p FROM macro_scheduling_slotlease WHERE token = r.prior_lease_id;
    IF r.slot_id IS DISTINCT FROM NEW.id OR r.owner_id IS DISTINCT FROM NEW.owner_id
     OR r.initial_lease_token IS DISTINCT FROM l.token OR p.sequence IS DISTINCT FROM OLD.attempt_count THEN
     RAISE EXCEPTION 'blocked transition requires its exact fresh recovery evidence' USING ERRCODE = '23514';
    END IF;
   END IF;
  ELSIF NEW.state IN ('completed', 'blocked') THEN
   SELECT status INTO outcome FROM macro_scheduling_slotoutcome WHERE lease_id = OLD.active_token;
   IF OLD.state <> 'running' OR NEW.attempt_count <> OLD.attempt_count OR outcome IS NULL
    OR outcome = 'expired' OR (NEW.state = 'completed') IS DISTINCT FROM (outcome = 'completed') THEN
    RAISE EXCEPTION 'slot terminal state requires the matching retained outcome' USING ERRCODE = '23514';
   END IF;
  ELSE
   RAISE EXCEPTION 'slot cannot return to pending' USING ERRCODE = '23514';
  END IF;
 END IF;
 RETURN NEW;
END $$;

CREATE TRIGGER schedule_slotrecovery_immutable BEFORE UPDATE OR DELETE ON macro_scheduling_slotrecovery FOR EACH ROW EXECUTE FUNCTION schedule_immutable();
CREATE TRIGGER schedule_slotrecovery_insert BEFORE INSERT ON macro_scheduling_slotrecovery FOR EACH ROW EXECUTE FUNCTION schedule_insert_guard();
"""

REVERSE = """
DROP TRIGGER schedule_slotrecovery_immutable ON macro_scheduling_slotrecovery;
DROP TRIGGER schedule_slotrecovery_insert ON macro_scheduling_slotrecovery;
CREATE OR REPLACE FUNCTION schedule_insert_guard() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE w macro_scheduling_watchrecord; s macro_scheduling_scheduledslot;
 v macro_scheduling_watchversion; l macro_scheduling_slotlease; expected_owner uuid;
BEGIN
 IF TG_TABLE_NAME = 'macro_scheduling_watchrecord' THEN
  SELECT owner_id INTO expected_owner FROM macro_theses WHERE id = NEW.thesis_id;
  IF NEW.owner_id IS DISTINCT FROM expected_owner OR NEW.revision <> 0 OR NEW.current_version_id IS NOT NULL THEN
   RAISE EXCEPTION 'watch must begin in its owner thesis scope' USING ERRCODE = '23514';
  END IF;
 ELSIF TG_TABLE_NAME = 'macro_scheduling_watchversion' THEN
  SELECT * INTO w FROM macro_scheduling_watchrecord WHERE id = NEW.watch_id;
  IF NEW.owner_id IS DISTINCT FROM w.owner_id OR NEW.sequence <> w.revision + 1
   OR NEW.created_at < w.changed_at OR jsonb_typeof(NEW.configuration) <> 'object'
   OR NEW.configuration->>'schema_version' IS DISTINCT FROM 'internal-desk-watch-v1' THEN
   RAISE EXCEPTION 'watch version scope/time/configuration mismatch' USING ERRCODE = '23514';
  END IF;
 ELSIF TG_TABLE_NAME = 'macro_scheduling_scheduledslot' THEN
  SELECT * INTO w FROM macro_scheduling_watchrecord WHERE id = NEW.watch_id;
  SELECT * INTO v FROM macro_scheduling_watchversion WHERE id = NEW.watch_version_id;
  IF NEW.owner_id IS DISTINCT FROM w.owner_id OR NEW.thesis_id IS DISTINCT FROM w.thesis_id
   OR v.watch_id IS DISTINCT FROM w.id OR NEW.watch_version_id IS DISTINCT FROM w.current_version_id
   OR NEW.created_at < w.changed_at OR NEW.state <> 'pending' OR NEW.attempt_count <> 0
   OR NEW.active_token IS NOT NULL OR NEW.lease_until IS NOT NULL
   OR NEW.late IS DISTINCT FROM (NEW.created_at > NEW.intended_at)
   OR (NEW.kind = 'daily_review' AND NEW.identity_key <> 'daily_review:' || NEW.local_date::text) THEN
   RAISE EXCEPTION 'slot must begin pending with exact watch scope and honest lateness' USING ERRCODE = '23514';
  END IF;
 ELSIF TG_TABLE_NAME = 'macro_scheduling_slotlease' THEN
  SELECT * INTO s FROM macro_scheduling_scheduledslot WHERE id = NEW.slot_id;
  SELECT * INTO v FROM macro_scheduling_watchversion WHERE id = s.watch_version_id;
  IF NEW.sequence <> s.attempt_count + 1 OR NEW.admitted_at < s.created_at
   OR s.state NOT IN ('pending', 'running')
   OR NEW.deadline_at IS DISTINCT FROM NEW.admitted_at + (v.configuration->>'lease_seconds')::integer * interval '1 second'
   OR (NEW.mode = 'recover') IS DISTINCT FROM EXISTS (SELECT 1 FROM macro_scheduling_analysisdispatch WHERE slot_id = s.id) THEN
   RAISE EXCEPTION 'lease scope/time/mode mismatch' USING ERRCODE = '23514';
  END IF;
  IF s.state = 'running' AND (s.lease_until > NEW.admitted_at OR NOT EXISTS
    (SELECT 1 FROM macro_scheduling_slotoutcome WHERE lease_id = s.active_token AND status = 'expired')) THEN
   RAISE EXCEPTION 'live lease cannot be replaced without expired outcome' USING ERRCODE = '23514';
  END IF;
 ELSIF TG_TABLE_NAME = 'macro_scheduling_slotoutcome' THEN
  SELECT * INTO l FROM macro_scheduling_slotlease WHERE token = NEW.lease_id;
  SELECT * INTO s FROM macro_scheduling_scheduledslot WHERE id = l.slot_id;
  IF s.state <> 'running' OR s.active_token IS DISTINCT FROM l.token OR NEW.finished_at < l.admitted_at
   OR jsonb_typeof(NEW.payload) <> 'object'
   OR (NEW.status = 'expired' AND NEW.finished_at < l.deadline_at)
   OR (NEW.status <> 'expired' AND NEW.finished_at >= l.deadline_at) THEN
   RAISE EXCEPTION 'outcome must preserve the protected active lease ordering' USING ERRCODE = '23514';
  END IF;
 ELSIF TG_TABLE_NAME = 'macro_scheduling_analysisdispatch' THEN
  SELECT * INTO s FROM macro_scheduling_scheduledslot WHERE id = NEW.slot_id;
  SELECT * INTO l FROM macro_scheduling_slotlease WHERE token = NEW.lease_id;
  SELECT * INTO v FROM macro_scheduling_watchversion WHERE id = s.watch_version_id;
  IF s.kind <> 'analysis' OR s.state <> 'running' OR s.active_token IS DISTINCT FROM l.token
   OR l.slot_id IS DISTINCT FROM s.id OR l.mode <> 'execute'
   OR NEW.started_at < l.admitted_at OR NEW.started_at >= l.deadline_at
   OR jsonb_typeof(NEW.request) <> 'object'
   OR NEW.request->>'expected_approval_id' IS DISTINCT FROM v.configuration->>'approval_id'
   OR NEW.request->>'expected_exposure_digest' IS DISTINCT FROM v.configuration->>'exposure_digest'
   OR NEW.request->>'provider' IS DISTINCT FROM v.configuration->>'provider'
   OR NEW.request->>'model_id' IS DISTINCT FROM v.configuration->>'model_id'
   OR NEW.request->'model_configuration' IS DISTINCT FROM v.configuration->'model_configuration'
   OR NOT EXISTS (SELECT 1 FROM jsonb_array_elements(v.configuration->'sources') source
      WHERE source->>'source_id' = NEW.request->>'source_id') THEN
   RAISE EXCEPTION 'analysis dispatch must bind its exact active lease and configured request' USING ERRCODE = '23514';
  END IF;
 END IF;
 RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION schedule_state_guard() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE v macro_scheduling_watchversion; l macro_scheduling_slotlease; outcome varchar;
BEGIN
 IF TG_TABLE_NAME = 'macro_scheduling_watchrecord' THEN
  SELECT * INTO v FROM macro_scheduling_watchversion WHERE id = NEW.current_version_id;
  IF NEW.id <> OLD.id OR NEW.owner_id <> OLD.owner_id OR NEW.thesis_id <> OLD.thesis_id
   OR NEW.changed_at < OLD.changed_at OR NEW.next_capture_at < OLD.next_capture_at
   OR NEW.next_analysis_at < OLD.next_analysis_at OR NEW.next_daily_date < OLD.next_daily_date
   OR NEW.revision < OLD.revision OR NEW.revision > OLD.revision + 1
   OR v.watch_id IS DISTINCT FROM NEW.id OR v.sequence IS DISTINCT FROM NEW.revision
   OR (NEW.revision = OLD.revision AND NEW.current_version_id IS DISTINCT FROM OLD.current_version_id)
   OR (NEW.revision = OLD.revision + 1 AND (NEW.current_version_id IS NOT DISTINCT FROM OLD.current_version_id
       OR v.created_at IS DISTINCT FROM NEW.changed_at)) THEN
   RAISE EXCEPTION 'invalid watch state or cursor transition' USING ERRCODE = '23514';
  END IF;
 ELSIF TG_TABLE_NAME = 'macro_scheduling_scheduledslot' THEN
  IF (to_jsonb(NEW) - ARRAY['state','attempt_count','active_token','lease_until']) IS DISTINCT FROM
     (to_jsonb(OLD) - ARRAY['state','attempt_count','active_token','lease_until'])
   OR OLD.state IN ('completed', 'blocked') THEN
   RAISE EXCEPTION 'slot identity/input and terminal state are immutable' USING ERRCODE = '23514';
  END IF;
  IF NEW.state = 'running' THEN
   SELECT * INTO l FROM macro_scheduling_slotlease WHERE token = NEW.active_token;
   IF l.slot_id IS DISTINCT FROM NEW.id OR l.sequence IS DISTINCT FROM NEW.attempt_count
    OR l.deadline_at IS DISTINCT FROM NEW.lease_until OR NEW.attempt_count <> OLD.attempt_count + 1 THEN
    RAISE EXCEPTION 'slot running state requires its exact new lease' USING ERRCODE = '23514';
   END IF;
  ELSIF NEW.state IN ('completed', 'blocked') THEN
   SELECT status INTO outcome FROM macro_scheduling_slotoutcome WHERE lease_id = OLD.active_token;
   IF OLD.state <> 'running' OR NEW.attempt_count <> OLD.attempt_count OR outcome IS NULL
    OR outcome = 'expired' OR (NEW.state = 'completed') IS DISTINCT FROM (outcome = 'completed') THEN
    RAISE EXCEPTION 'slot terminal state requires the matching retained outcome' USING ERRCODE = '23514';
   END IF;
  ELSE
   RAISE EXCEPTION 'slot cannot return to pending' USING ERRCODE = '23514';
  END IF;
 END IF;
 RETURN NEW;
END $$;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('macro_scheduling', '0003_scheduling_guards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotRecovery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command_id', models.UUIDField()),
                ('action', models.CharField(choices=[('retry', 'retry'), ('reconcile', 'reconcile')], max_length=16)),
                ('reason', models.CharField(max_length=2000)),
                ('created_at', models.DateTimeField()),
                ('request_digest', models.CharField(max_length=64)),
                ('initial_lease_token', models.UUIDField(unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('prior_lease', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='manual_recovery', to='macro_scheduling.slotlease')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recoveries', to='macro_scheduling.scheduledslot')),
                ('watch_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='macro_scheduling.watchversion')),
            ],
        ),
        migrations.AddField(
            model_name='slotlease',
            name='recovery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='macro_scheduling.slotrecovery'),
        ),
        migrations.AddConstraint(
            model_name='slotrecovery',
            constraint=models.UniqueConstraint(fields=('owner', 'command_id'), name='schedule_recovery_command'),
        ),
        migrations.AddConstraint(
            model_name='slotrecovery',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ('retry', 'reconcile'))), name='schedule_recovery_action'),
        ),
        migrations.AddConstraint(
            model_name='slotrecovery',
            constraint=models.CheckConstraint(condition=models.Q(('request_digest__regex', '^[0-9a-f]{64}$')), name='schedule_recovery_digest'),
        ),
        migrations.RunSQL(SQL, REVERSE),
    ]
