# Generated by Django 5.2.17 on 2026-10-07 11:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveBigIntegerField()),
                ('admitted_at', models.DateTimeField()),
                ('deadline_at', models.DateTimeField()),
                ('contract_digest', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SourceRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('observation_revision', models.PositiveIntegerField()),
                ('digest', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('source_claimed_published_at', models.DateTimeField(null=True)),
                ('system_received_at', models.DateTimeField()),
                ('capture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='macro_monitoring.captureattempt')),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningAttempt',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('admitted_at', models.DateTimeField()),
                ('deadline_at', models.DateTimeField()),
                ('rule_version', models.CharField(default='unclassified-preserve-v1', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SourceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('native_id', models.CharField(max_length=512)),
                ('revision_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SourceState',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('contract', models.JSONField()),
                ('contract_digest', models.CharField(max_length=64)),
                ('capture_sequence', models.PositiveBigIntegerField(default=0)),
                ('active_capture', models.UUIDField(null=True)),
                ('last_successful_capture_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DurableObservation',
            fields=[
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='macro_monitoring.sourcerevision')),
                ('observed_by_at', models.DateTimeField()),
                ('method', models.CharField(default='postcommit_read', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningResult',
            fields=[
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='macro_monitoring.screeningattempt')),
                ('finished_at', models.DateTimeField()),
                ('decision', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='sourcerevision',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='macro_monitoring.sourcereport'),
        ),
        migrations.AddField(
            model_name='sourcereport',
            name='current_revision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_heads', to='macro_monitoring.sourcerevision'),
        ),
        migrations.AddField(
            model_name='sourcereport',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='macro_monitoring.sourcestate'),
        ),
        migrations.AddField(
            model_name='captureattempt',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='macro_monitoring.sourcestate'),
        ),
        migrations.CreateModel(
            name='CaptureOutcome',
            fields=[
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='macro_monitoring.captureattempt')),
                ('status', models.CharField(choices=[('captured', 'captured'), ('failed', 'failed'), ('outcome_unknown', 'outcome_unknown')], max_length=32)),
                ('code', models.CharField(max_length=64)),
                ('finished_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(null=True)),
                ('transport_digest', models.CharField(max_length=64, null=True)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('new_revision_count', models.PositiveIntegerField(default=0)),
                ('coverage', models.CharField(default='bounded_snapshot', max_length=32)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ('captured', 'failed', 'outcome_unknown'))), name='monitor_capture_status')],
            },
        ),
        migrations.CreateModel(
            name='ScreeningWork',
            fields=[
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='macro_monitoring.sourcerevision')),
                ('state', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('completed', 'completed'), ('superseded', 'superseded')], default='pending', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('active_token', models.UUIDField(null=True)),
                ('lease_until', models.DateTimeField(null=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('state__in', ('pending', 'running', 'completed', 'superseded'))), name='monitor_work_status'), models.CheckConstraint(condition=models.Q(models.Q(('active_token__isnull', False), ('lease_until__isnull', False), ('state', 'running')), models.Q(models.Q(('state', 'running'), _negated=True), ('active_token__isnull', True), ('lease_until__isnull', True)), _connector='OR'), name='monitor_work_lease_state')],
            },
        ),
        migrations.AddField(
            model_name='screeningattempt',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='macro_monitoring.screeningwork'),
        ),
        migrations.CreateModel(
            name='CaptureMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='macro_monitoring.captureattempt')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='macro_monitoring.sourcerevision')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('capture', 'revision'), name='monitor_capture_membership')],
            },
        ),
        migrations.AddConstraint(
            model_name='sourcerevision',
            constraint=models.UniqueConstraint(fields=('report', 'digest'), name='monitor_payload_identity'),
        ),
        migrations.AddConstraint(
            model_name='sourcerevision',
            constraint=models.UniqueConstraint(fields=('report', 'observation_revision'), name='monitor_observation_order'),
        ),
        migrations.AddConstraint(
            model_name='sourcerevision',
            constraint=models.UniqueConstraint(fields=('report', 'id'), name='monitor_revision_scope'),
        ),
        migrations.AddConstraint(
            model_name='sourcerevision',
            constraint=models.CheckConstraint(condition=models.Q(('observation_revision__gt', 0)), name='monitor_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='sourcerevision',
            constraint=models.CheckConstraint(condition=models.Q(('digest__regex', '^[0-9a-f]{64}$')), name='monitor_revision_digest'),
        ),
        migrations.AddConstraint(
            model_name='sourcereport',
            constraint=models.UniqueConstraint(fields=('source', 'native_id'), name='monitor_native_identity'),
        ),
        migrations.AddConstraint(
            model_name='captureattempt',
            constraint=models.UniqueConstraint(fields=('source', 'sequence'), name='monitor_capture_sequence'),
        ),
        migrations.AddConstraint(
            model_name='captureattempt',
            constraint=models.CheckConstraint(condition=models.Q(('deadline_at__gt', models.F('admitted_at'))), name='monitor_capture_deadline'),
        ),
        migrations.AddConstraint(
            model_name='screeningattempt',
            constraint=models.UniqueConstraint(fields=('work', 'sequence'), name='monitor_screen_sequence'),
        ),
        migrations.AddConstraint(
            model_name='screeningattempt',
            constraint=models.CheckConstraint(condition=models.Q(('deadline_at__gt', models.F('admitted_at'))), name='monitor_screen_deadline'),
        ),
    ]
