# Generated by Django 5.2.17 on 2026-10-07 17:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macro_monitoring', '0003_recovery_guards'),
        ('macro_theses', '0002_model_compilation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAnalysisAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command_id', models.UUIDField()),
                ('exposure_digest', models.CharField(max_length=64)),
                ('request_digest', models.CharField(max_length=64)),
                ('resolved_inputs', models.JSONField()),
                ('context', models.JSONField()),
                ('context_digest', models.CharField(max_length=64)),
                ('messages', models.JSONField()),
                ('prompt_digest', models.CharField(max_length=64)),
                ('provider', models.CharField(max_length=32)),
                ('model_id', models.CharField(max_length=255)),
                ('model_metadata', models.JSONField()),
                ('configuration', models.JSONField()),
                ('created_at', models.DateTimeField()),
                ('deadline_at', models.DateTimeField()),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='macro_theses.approvalrecord')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('source_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='macro_monitoring.sourcerevision')),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='macro_theses.thesisrecord')),
            ],
        ),
        migrations.CreateModel(
            name='NewsAnalysisResult',
            fields=[
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='result', serialize=False, to='macro_monitoring.newsanalysisattempt')),
                ('status', models.CharField(max_length=32)),
                ('stop_reason', models.CharField(max_length=64)),
                ('finished_at', models.DateTimeField()),
                ('document', models.JSONField(null=True)),
                ('provider_metadata', models.JSONField()),
                ('stale_reasons', models.JSONField()),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ('analysed', 'stale', 'failed', 'outcome_unknown'))), name='monitor_analysis_result_status'), models.CheckConstraint(condition=models.Q(models.Q(('status__in', ('analysed', 'stale')), _negated=True), ('document__isnull', False), _connector='OR'), name='monitor_analysis_document')],
            },
        ),
        migrations.AddConstraint(
            model_name='newsanalysisattempt',
            constraint=models.UniqueConstraint(fields=('owner', 'command_id'), name='monitor_analysis_command'),
        ),
        migrations.AddConstraint(
            model_name='newsanalysisattempt',
            constraint=models.UniqueConstraint(fields=('thesis', 'approval', 'exposure_digest', 'source_revision'), name='monitor_analysis_input_once'),
        ),
        migrations.AddConstraint(
            model_name='newsanalysisattempt',
            constraint=models.CheckConstraint(condition=models.Q(('deadline_at__gt', models.F('created_at'))), name='monitor_analysis_deadline'),
        ),
        migrations.AddConstraint(
            model_name='newsanalysisattempt',
            constraint=models.CheckConstraint(condition=models.Q(('provider__in', ('nanogpt', 'openrouter', 'cheaperinference'))), name='monitor_analysis_provider'),
        ),
    ]
