# Generated by Django 5.2.17 on 2026-10-07 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macro_monitoring', '0004_newsanalysisattempt_newsanalysisresult_and_more'),
        ('macro_theses', '0002_model_compilation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsReviewReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_id', models.UUIDField()),
                ('request_digest', models.CharField(max_length=64)),
                ('empty_response', models.JSONField(null=True)),
                ('saved_at', models.DateTimeField()),
                ('attempt', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='macro_monitoring.newsanalysisattempt')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='macro_theses.thesisrecord')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'command_id'), name='monitor_news_receipt_identity'), models.CheckConstraint(condition=models.Q(models.Q(('attempt__isnull', False), ('empty_response__isnull', True)), models.Q(('attempt__isnull', True), ('empty_response__isnull', False)), _connector='OR'), name='monitor_news_receipt_outcome')],
            },
        ),
    ]
