# Generated by Django 5.2.17 on 2026-10-10 16:38

import django.db.models.deletion
from django.db import migrations, models


SQL = """
ALTER TABLE macro_monitoring_newsanalysisattempt ADD CONSTRAINT monitor_analysis_context_scope
 FOREIGN KEY (admission_context_id, owner_id, thesis_id)
 REFERENCES macro_desk_privatecontext(id, owner_id, thesis_id) DEFERRABLE INITIALLY IMMEDIATE;

CREATE FUNCTION monitor_cumulative_admission_guard() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE pinned macro_desk_privatecontext%ROWTYPE;
BEGIN
 IF NEW.admission_context_id IS NULL THEN
  IF NEW.context ? 'cumulative' OR NEW.configuration ->> 'context' = 'complete_retained_context' THEN
   RAISE EXCEPTION 'cumulative admission requires a retained private context' USING ERRCODE = '23514';
  END IF;
 ELSE
  SELECT * INTO pinned FROM macro_desk_privatecontext WHERE id = NEW.admission_context_id;
  IF pinned.id IS NULL OR pinned.owner_id IS DISTINCT FROM NEW.owner_id
   OR pinned.thesis_id IS DISTINCT FROM NEW.thesis_id OR pinned.approval_id IS DISTINCT FROM NEW.approval_id
   OR pinned.exposure_digest IS DISTINCT FROM NEW.exposure_digest OR pinned.prepared_at IS DISTINCT FROM NEW.created_at
   OR NEW.configuration ->> 'context' IS DISTINCT FROM 'complete_retained_context'
   OR NEW.configuration ->> 'schema_version' IS DISTINCT FROM 'retained-news-analysis-v2'
   OR NEW.configuration ->> 'prompt_version' IS DISTINCT FROM 'retained-news-analysis-prompt-v3'
   OR NEW.context -> 'cumulative' IS DISTINCT FROM pinned.resolved_inputs -> 'cumulative'
   OR NEW.context #>> '{cumulative,context_id}' IS DISTINCT FROM pinned.id::text
   OR COALESCE(NEW.context #>> '{cumulative,digest}', '') !~ '^[0-9a-f]{64}$'
   OR NOT EXISTS (SELECT 1 FROM macro_desk_evidencerevision member
     WHERE member.evidence_id = pinned.evidence_id AND member.revision_id = NEW.source_revision_id)
   OR NOT EXISTS (SELECT 1 FROM jsonb_array_elements(NEW.context #> '{cumulative,reports}') item
     WHERE item ->> 'revision_id' = NEW.source_revision_id::text) THEN
   RAISE EXCEPTION 'cumulative admission context authority or evidence mismatch' USING ERRCODE = '23514';
  END IF;
 END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER monitor_cumulative_admission_scope BEFORE INSERT ON macro_monitoring_newsanalysisattempt
 FOR EACH ROW EXECUTE FUNCTION monitor_cumulative_admission_guard();
"""
REVERSE = """
DROP TRIGGER monitor_cumulative_admission_scope ON macro_monitoring_newsanalysisattempt;
DROP FUNCTION monitor_cumulative_admission_guard();
ALTER TABLE macro_monitoring_newsanalysisattempt DROP CONSTRAINT monitor_analysis_context_scope;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('macro_desk', '0004_context_exposure'),
        ('macro_monitoring', '0006_news_evidence_guards'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsanalysisattempt',
            name='admission_context',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='news_analysis_attempts', to='macro_desk.privatecontext'),
        ),
        migrations.RunSQL(SQL, REVERSE),
    ]
