# Generated by Django 5.2.17 on 2026-10-05 16:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


GUARDS_SQL = """
ALTER TABLE macro_thesis_brief_bindings ADD CONSTRAINT macro_binding_brief_owner_fk
 FOREIGN KEY (brief_id, owner_id) REFERENCES macro_brief_states (brief_id, owner_id)
 DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE macro_thesis_brief_bindings ADD CONSTRAINT macro_binding_thesis_owner_fk
 FOREIGN KEY (thesis_id, owner_id) REFERENCES macro_theses (id, owner_id)
 DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE macro_thesis_brief_bindings ADD CONSTRAINT macro_binding_approval_scope_fk
 FOREIGN KEY (thesis_id, admitted_approval_id) REFERENCES macro_thesis_approvals (thesis_id, id)
 DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE macro_context_admissions ADD CONSTRAINT macro_admission_binding_scope_fk
 FOREIGN KEY (brief_id, thesis_id) REFERENCES macro_thesis_brief_bindings (brief_id, thesis_id)
 DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE macro_context_admissions ADD CONSTRAINT macro_admission_approval_scope_fk
 FOREIGN KEY (thesis_id, approval_id) REFERENCES macro_thesis_approvals (thesis_id, id)
 DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE macro_thesis_brief_bindings ADD CONSTRAINT macro_binding_admitted_context_fk
 FOREIGN KEY (brief_id, admitted_approval_id, admitted_exposure_digest)
 REFERENCES macro_context_admissions (brief_id, approval_id, exposure_digest)
 DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE macro_context_admissions ADD CONSTRAINT macro_admission_inputs_object
 CHECK (jsonb_typeof(resolved_inputs) = 'object');
ALTER TABLE macro_context_admissions ADD CONSTRAINT macro_admission_pins_array
 CHECK (jsonb_typeof(pins) = 'array');
CREATE TRIGGER macro_context_admission_immutable
 BEFORE UPDATE OR DELETE ON macro_context_admissions
 FOR EACH ROW EXECUTE FUNCTION macro_agent_reject_history_change();
CREATE FUNCTION macro_agent_guard_binding_identity() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
 IF TG_OP = 'DELETE' THEN
  RAISE EXCEPTION 'thesis binding cannot be deleted' USING ERRCODE = '23514';
 END IF;
 IF ROW(NEW.brief_id, NEW.thesis_id, NEW.owner_id, NEW.created_at)
    IS DISTINCT FROM ROW(OLD.brief_id, OLD.thesis_id, OLD.owner_id, OLD.created_at) THEN
  RAISE EXCEPTION 'thesis binding identity is immutable' USING ERRCODE = '23514';
 END IF;
 IF OLD.observed_at IS NOT NULL AND (NEW.observed_at IS NULL OR NEW.observed_at < OLD.observed_at) THEN
  RAISE EXCEPTION 'context observation cannot move backwards' USING ERRCODE = '23514';
 END IF;
 RETURN NEW;
END;
$$;
CREATE TRIGGER macro_thesis_binding_identity_guard
 BEFORE UPDATE OR DELETE ON macro_thesis_brief_bindings
 FOR EACH ROW EXECUTE FUNCTION macro_agent_guard_binding_identity();
"""

REVERSE_GUARDS_SQL = """
DROP TRIGGER macro_thesis_binding_identity_guard ON macro_thesis_brief_bindings;
DROP FUNCTION macro_agent_guard_binding_identity();
DROP TRIGGER macro_context_admission_immutable ON macro_context_admissions;
ALTER TABLE macro_context_admissions DROP CONSTRAINT macro_admission_pins_array;
ALTER TABLE macro_context_admissions DROP CONSTRAINT macro_admission_inputs_object;
ALTER TABLE macro_thesis_brief_bindings DROP CONSTRAINT macro_binding_admitted_context_fk;
ALTER TABLE macro_context_admissions DROP CONSTRAINT macro_admission_approval_scope_fk;
ALTER TABLE macro_context_admissions DROP CONSTRAINT macro_admission_binding_scope_fk;
ALTER TABLE macro_thesis_brief_bindings DROP CONSTRAINT macro_binding_approval_scope_fk;
ALTER TABLE macro_thesis_brief_bindings DROP CONSTRAINT macro_binding_thesis_owner_fk;
ALTER TABLE macro_thesis_brief_bindings DROP CONSTRAINT macro_binding_brief_owner_fk;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('macro_persistence', '0002_lifecycle_guards'),
        ('macro_theses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='briefstaterecord',
            constraint=models.UniqueConstraint(fields=('brief_id', 'owner'), name='macro_brief_owner_target'),
        ),
        migrations.CreateModel(
            name='ContextAdmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exposure_digest', models.CharField(max_length=64)),
                ('input_digest', models.CharField(max_length=64)),
                ('input_observed_at', models.DateTimeField()),
                ('admission_effective_at', models.DateTimeField()),
                ('resolved_inputs', models.JSONField()),
                ('pins', models.JSONField()),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='context_admissions', to='macro_theses.approvalrecord')),
                ('brief', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='context_admissions', to='macro_persistence.briefstaterecord')),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='context_admissions', to='macro_theses.thesisrecord')),
            ],
            options={
                'db_table': 'macro_context_admissions',
                'constraints': [models.UniqueConstraint(fields=('brief', 'approval', 'exposure_digest'), name='macro_admission_context_identity'), models.CheckConstraint(condition=models.Q(('exposure_digest__regex', '^[0-9a-f]{64}$')), name='macro_admission_exposure_digest'), models.CheckConstraint(condition=models.Q(('input_digest__regex', '^[0-9a-f]{64}$')), name='macro_admission_input_digest'), models.CheckConstraint(condition=models.Q(('admission_effective_at__gte', models.F('input_observed_at'))), name='macro_admission_time_order')],
            },
        ),
        migrations.CreateModel(
            name='ThesisBriefBinding',
            fields=[
                ('brief', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='thesis_binding', serialize=False, to='macro_persistence.briefstaterecord')),
                ('created_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('ready', 'ready')], max_length=16)),
                ('admitted_exposure_digest', models.CharField(max_length=64, null=True)),
                ('observed_at', models.DateTimeField(null=True)),
                ('admitted_approval', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='brief_bindings', to='macro_theses.approvalrecord')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thesis_brief_bindings', to=settings.AUTH_USER_MODEL)),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brief_bindings', to='macro_theses.thesisrecord')),
            ],
            options={
                'db_table': 'macro_thesis_brief_bindings',
                'constraints': [models.UniqueConstraint(fields=('brief', 'thesis'), name='macro_binding_thesis_target'), models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'ready'))), name='macro_binding_status_allowed'), models.CheckConstraint(condition=models.Q(('status', 'pending'), models.Q(('admitted_approval__isnull', False), ('admitted_exposure_digest__isnull', False), ('admitted_exposure_digest__regex', '^[0-9a-f]{64}$'), ('observed_at__isnull', False), ('status', 'ready')), _connector='OR'), name='macro_binding_ready_inputs'), models.CheckConstraint(condition=models.Q(('observed_at__isnull', True), ('observed_at__gte', models.F('created_at')), _connector='OR'), name='macro_binding_observation_order')],
            },
        ),
        migrations.RunSQL(GUARDS_SQL, reverse_sql=REVERSE_GUARDS_SQL),
    ]
