# Generated by Django 5.2.17 on 2026-10-09 21:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('macro_monitoring', '0006_news_evidence_guards'),
        ('macro_theses', '0003_review_card_refinement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResultObservation',
            fields=[
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='macro_monitoring.newsanalysisresult')),
                ('observed_by_at', models.DateTimeField()),
                ('method', models.CharField(default='postcommit_read', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('cutoff', models.DateTimeField()),
                ('prepared_at', models.DateTimeField()),
                ('policy_version', models.CharField(default='complete-retained-sources-v1', max_length=64)),
                ('limits', models.JSONField()),
                ('source_manifest', models.JSONField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='macro_theses.thesisrecord')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='macro_monitoring.newsanalysisattempt')),
                ('result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='macro_monitoring.newsanalysisresult')),
                ('witness', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='macro_desk.analysisresultobservation')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analyses', to='macro_desk.evidenceset')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateContext',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exposure_digest', models.CharField(max_length=64)),
                ('resolved_inputs', models.JSONField()),
                ('prepared_at', models.DateTimeField()),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='macro_theses.approvalrecord')),
                ('evidence', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='macro_desk.evidenceset')),
                ('interpretation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='macro_theses.interpretationrecord')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('predecessor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='macro_desk.privatecontext')),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='macro_theses.thesisrecord')),
            ],
        ),
        migrations.CreateModel(
            name='DailyReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command_id', models.UUIDField()),
                ('request_digest', models.CharField(max_length=64)),
                ('start', models.DateTimeField()),
                ('cutoff', models.DateTimeField()),
                ('prepared_at', models.DateTimeField()),
                ('content', models.JSONField()),
                ('digest', models.CharField(max_length=64)),
                ('original_outcome', models.CharField(default='prepared', max_length=32)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='macro_theses.thesisrecord')),
                ('context', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='macro_desk.privatecontext')),
            ],
        ),
        migrations.CreateModel(
            name='SourceContractVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract', models.JSONField()),
                ('digest', models.CharField(max_length=64)),
                ('permitted', models.BooleanField()),
                ('provenance', models.CharField(max_length=64)),
                ('reason', models.TextField()),
                ('observed_at', models.DateTimeField()),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='macro_monitoring.sourcestate')),
            ],
        ),
        migrations.CreateModel(
            name='SourceContractHead',
            fields=[
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='macro_monitoring.sourcestate')),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='macro_desk.sourcecontractversion')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='macro_desk.evidenceset')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='macro_monitoring.sourcestate')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='macro_desk.sourcecontractversion')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_at_preparation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='macro_monitoring.sourcerevision')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='macro_monitoring.sourcerevision')),
                ('witness', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='macro_monitoring.durableobservation')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='macro_desk.evidenceset')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='macro_desk.sourcecontractversion')),
            ],
        ),
        migrations.AddConstraint(
            model_name='evidenceset',
            constraint=models.CheckConstraint(condition=models.Q(('cutoff__gt', models.F('start')), ('prepared_at__gte', models.F('cutoff'))), name='desk_evidence_period'),
        ),
        migrations.AddConstraint(
            model_name='evidenceset',
            constraint=models.UniqueConstraint(fields=('id', 'owner', 'thesis'), name='desk_evidence_scope_target'),
        ),
        migrations.AddConstraint(
            model_name='evidenceanalysis',
            constraint=models.UniqueConstraint(fields=('evidence', 'attempt'), name='desk_evidence_analysis_once'),
        ),
        migrations.AddConstraint(
            model_name='privatecontext',
            constraint=models.UniqueConstraint(fields=('id', 'owner', 'thesis'), name='desk_context_scope_target'),
        ),
        migrations.AddConstraint(
            model_name='dailyreview',
            constraint=models.UniqueConstraint(fields=('owner', 'command_id'), name='desk_review_command_once'),
        ),
        migrations.AddConstraint(
            model_name='dailyreview',
            constraint=models.UniqueConstraint(fields=('thesis', 'cutoff'), name='desk_review_cutoff_once'),
        ),
        migrations.AddConstraint(
            model_name='dailyreview',
            constraint=models.CheckConstraint(condition=models.Q(('original_outcome', 'prepared')), name='desk_review_original_outcome'),
        ),
        migrations.AddConstraint(
            model_name='sourcecontractversion',
            constraint=models.UniqueConstraint(fields=('source', 'id'), name='desk_contract_scope_target'),
        ),
        migrations.AddConstraint(
            model_name='evidencesource',
            constraint=models.UniqueConstraint(fields=('evidence', 'source'), name='desk_evidence_source_once'),
        ),
        migrations.AddConstraint(
            model_name='evidencerevision',
            constraint=models.UniqueConstraint(fields=('evidence', 'revision'), name='desk_evidence_revision_once'),
        ),
    ]
