# Generated by Django 5.2.17 on 2026-10-09 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macro_desk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcecontractversion',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='macro_desk.sourcecontractversion'),
        ),
    ]
