# Generated by Django 5.2.17 on 2026-10-09 21:53

import django.db.models.deletion
from django.db import migrations, models


SQL = """
ALTER TABLE macro_desk_contextexposure ADD CONSTRAINT desk_exposure_version_scope_fk
 FOREIGN KEY (position_id, version_id) REFERENCES macro_paper_position_versions(position_id, id)
 DEFERRABLE INITIALLY IMMEDIATE;
CREATE FUNCTION desk_exposure_guard() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE actual_owner uuid; actual_thesis uuid; version_digest varchar;
BEGIN
 SELECT owner_id,thesis_id,digest INTO actual_owner,actual_thesis,version_digest
  FROM macro_paper_position_versions WHERE id=NEW.version_id;
 IF NOT EXISTS (SELECT 1 FROM macro_desk_privatecontext c,
  jsonb_array_elements(c.resolved_inputs #> '{approved_user,exposure,positions}') member
  WHERE c.id=NEW.context_id AND c.owner_id=actual_owner AND c.thesis_id=actual_thesis
   AND member->>'position_id'=NEW.position_id::text
   AND member->>'version_id'=NEW.version_id::text AND member->>'version_digest'=version_digest) THEN
  RAISE EXCEPTION 'context exposure does not match exact scoped inputs' USING ERRCODE='23514';
 END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER desk_exposure_scope BEFORE INSERT ON macro_desk_contextexposure
 FOR EACH ROW EXECUTE FUNCTION desk_exposure_guard();
CREATE TRIGGER desk_exposure_immutable BEFORE UPDATE OR DELETE ON macro_desk_contextexposure
 FOR EACH ROW EXECUTE FUNCTION desk_reject_change();
CREATE FUNCTION desk_review_exposure_guard() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE originals jsonb; actual_count bigint;
BEGIN
 SELECT resolved_inputs #> '{approved_user,exposure,positions}' INTO originals
  FROM macro_desk_privatecontext WHERE id=NEW.context_id;
 SELECT count(*) INTO actual_count FROM macro_desk_contextexposure WHERE context_id=NEW.context_id;
 IF jsonb_typeof(originals) IS DISTINCT FROM 'array'
  OR actual_count<>jsonb_array_length(originals)
  OR jsonb_typeof(NEW.content #> '{scope,exposure_version_ids}') IS DISTINCT FROM 'array'
  OR actual_count<>jsonb_array_length(NEW.content #> '{scope,exposure_version_ids}')
  OR EXISTS (SELECT 1 FROM macro_desk_contextexposure member WHERE member.context_id=NEW.context_id
   AND NOT ((NEW.content #> '{scope,exposure_version_ids}') ? member.version_id::text)) THEN
  RAISE EXCEPTION 'daily review must retain the complete exact exposure membership' USING ERRCODE='23514';
 END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER desk_review_exposure_scope BEFORE INSERT ON macro_desk_dailyreview
 FOR EACH ROW EXECUTE FUNCTION desk_review_exposure_guard();
"""

REVERSE = """
DROP TRIGGER desk_review_exposure_scope ON macro_desk_dailyreview;
DROP FUNCTION desk_review_exposure_guard();
DROP TRIGGER desk_exposure_scope ON macro_desk_contextexposure;
DROP TRIGGER desk_exposure_immutable ON macro_desk_contextexposure;
DROP FUNCTION desk_exposure_guard();
ALTER TABLE macro_desk_contextexposure DROP CONSTRAINT desk_exposure_version_scope_fk;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('macro_desk', '0003_evidence_guards'),
        ('macro_positions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextExposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='macro_desk.privatecontext')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='macro_positions.positionrecord')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='macro_positions.positionversion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('context', 'position'), name='desk_context_position_once')],
            },
        ),
        migrations.RunSQL(SQL, REVERSE),
    ]
