# Generated by Django 5.2.17 on 2026-10-05 16:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


IMMUTABLE_TABLES = (
    "macro_paper_position_versions", "macro_paper_position_command_receipts",
    "macro_paper_position_audit_transitions",
)
SCOPED_CONSTRAINTS = (
    ("macro_paper_positions", "macro_position_owner_scope_fk", "(thesis_id, owner_id)",
     "macro_theses", "(id, owner_id)"),
    ("macro_paper_positions", "macro_position_original_approval_fk", "(thesis_id, original_approval_id)",
     "macro_thesis_approvals", "(thesis_id, id)"),
    ("macro_paper_position_versions", "macro_position_version_scope_fk", "(position_id, thesis_id, owner_id)",
     "macro_paper_positions", "(id, thesis_id, owner_id)"),
    ("macro_paper_position_versions", "macro_position_reviewed_approval_fk", "(thesis_id, reviewed_approval_id)",
     "macro_thesis_approvals", "(thesis_id, id)"),
    ("macro_paper_position_versions", "macro_position_parent_scope_fk", "(position_id, parent_id)",
     "macro_paper_position_versions", "(position_id, id)"),
    ("macro_paper_positions", "macro_position_current_scope_fk", "(id, current_version_id)",
     "macro_paper_position_versions", "(position_id, id)"),
    ("macro_paper_position_command_receipts", "macro_position_command_scope_fk", "(position_id, thesis_id, owner_id)",
     "macro_paper_positions", "(id, thesis_id, owner_id)"),
    ("macro_paper_position_audit_transitions", "macro_position_audit_scope_fk", "(position_id, thesis_id)",
     "macro_paper_positions", "(id, thesis_id)"),
)

GUARDS_SQL = """
CREATE FUNCTION macro_position_reject_history_change() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'immutable paper position history: %', TG_TABLE_NAME USING ERRCODE = '23514';
END;
$$;

CREATE FUNCTION macro_position_guard_identity_and_progress() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    proposed macro_paper_position_versions%ROWTYPE;
    previous macro_paper_position_versions%ROWTYPE;
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'durable paper position cannot be deleted' USING ERRCODE = '23514';
    END IF;
    IF ROW(NEW.id, NEW.owner_id, NEW.thesis_id, NEW.original_approval_id, NEW.created_at)
       IS DISTINCT FROM ROW(OLD.id, OLD.owner_id, OLD.thesis_id, OLD.original_approval_id, OLD.created_at) THEN
        RAISE EXCEPTION 'paper position identity, scope, and original approval are immutable'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.changed_at < OLD.changed_at THEN
        RAISE EXCEPTION 'position changed_at cannot move backwards' USING ERRCODE = '23514';
    END IF;
    IF NEW.current_version_id IS DISTINCT FROM OLD.current_version_id THEN
        IF NEW.revision <> OLD.revision + 1 THEN
            RAISE EXCEPTION 'a new position version requires the next aggregate revision'
                USING ERRCODE = '23514';
        END IF;
        SELECT * INTO proposed FROM macro_paper_position_versions WHERE id = NEW.current_version_id;
        IF NOT FOUND THEN
            RAISE EXCEPTION 'position version does not exist' USING ERRCODE = '23503';
        END IF;
        IF proposed.position_id <> NEW.id OR proposed.parent_id IS DISTINCT FROM OLD.current_version_id
           OR proposed.accepted_at IS DISTINCT FROM NEW.changed_at THEN
            RAISE EXCEPTION 'current version must preserve scope, parent, and effective time'
                USING ERRCODE = '23514';
        END IF;
        IF OLD.current_version_id IS NULL THEN
            IF proposed.status <> 'open' OR proposed.reviewed_approval_id <> NEW.original_approval_id THEN
                RAISE EXCEPTION 'an initial position must be open and use its original approval'
                    USING ERRCODE = '23514';
            END IF;
        ELSE
            SELECT * INTO previous FROM macro_paper_position_versions WHERE id = OLD.current_version_id;
            IF previous.status = 'closed' THEN
                RAISE EXCEPTION 'a closed paper position cannot be revised or reopened'
                    USING ERRCODE = '23514';
            END IF;
            IF proposed.status = 'closed' AND ROW(
                proposed.underlying, proposed.direction, proposed.product_id, proposed.venue,
                proposed.expiry, proposed.quote_currency, proposed.horizon, proposed.quantity,
                proposed.quantity_unit
            ) IS DISTINCT FROM ROW(
                previous.underlying, previous.direction, previous.product_id, previous.venue,
                previous.expiry, previous.quote_currency, previous.horizon, previous.quantity,
                previous.quantity_unit
            ) THEN
                RAISE EXCEPTION 'closing a position cannot revise exposure declarations'
                    USING ERRCODE = '23514';
            END IF;
        END IF;
    ELSIF NEW.revision <> OLD.revision OR NEW.changed_at IS DISTINCT FROM OLD.changed_at THEN
        RAISE EXCEPTION 'position progress requires a new immutable version' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER macro_position_identity_progress_guard
BEFORE UPDATE OR DELETE ON macro_paper_positions
FOR EACH ROW EXECUTE FUNCTION macro_position_guard_identity_and_progress();

CREATE FUNCTION macro_position_guard_version_time() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    created timestamptz;
    approved timestamptz;
    parent_time timestamptz;
    parent_status text;
BEGIN
    SELECT created_at INTO created FROM macro_paper_positions WHERE id = NEW.position_id;
    SELECT approved_at INTO approved FROM macro_thesis_approvals WHERE id = NEW.reviewed_approval_id;
    IF NEW.accepted_at < created OR NEW.accepted_at < approved THEN
        RAISE EXCEPTION 'position version cannot predate position or reviewed approval'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.parent_id IS NOT NULL THEN
        SELECT accepted_at, status INTO parent_time, parent_status
            FROM macro_paper_position_versions WHERE id = NEW.parent_id;
        IF NEW.accepted_at < parent_time OR parent_status = 'closed' THEN
            RAISE EXCEPTION 'position version cannot predate or follow a closed parent'
                USING ERRCODE = '23514';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER macro_position_version_time_guard
BEFORE INSERT ON macro_paper_position_versions
FOR EACH ROW EXECUTE FUNCTION macro_position_guard_version_time();

CREATE FUNCTION macro_position_is_date(value text) RETURNS boolean
LANGUAGE plpgsql IMMUTABLE STRICT AS $$
BEGIN
    IF value !~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' THEN
        RETURN FALSE;
    END IF;
    PERFORM make_date(substring(value, 1, 4)::integer, substring(value, 6, 2)::integer,
                      substring(value, 9, 2)::integer);
    RETURN TRUE;
EXCEPTION WHEN datetime_field_overflow THEN
    RETURN FALSE;
END;
$$;
ALTER TABLE macro_paper_position_versions ADD CONSTRAINT macro_position_expiry_date
    CHECK (macro_position_is_date(expiry));
ALTER TABLE macro_paper_position_versions ADD CONSTRAINT macro_position_quantity_bounds
    CHECK (CASE WHEN quantity ~ '^(0|[1-9][0-9]*)(\\.[0-9]+)?$' THEN
        quantity::numeric > 0
        AND length(replace(quantity, '.', '')) <= 28
        AND length(split_part(quantity, '.', 2)) <= 12
    ELSE quantity IS NULL END);
ALTER TABLE macro_paper_position_command_receipts ADD CONSTRAINT macro_position_command_result_object
    CHECK (jsonb_typeof(result) = 'object');
ALTER TABLE macro_paper_position_audit_transitions ADD CONSTRAINT macro_position_audit_detail_object
    CHECK (jsonb_typeof(detail) = 'object');
"""
for table in IMMUTABLE_TABLES:
    GUARDS_SQL += f"""
CREATE TRIGGER {table}_immutable BEFORE UPDATE OR DELETE ON {table}
FOR EACH ROW EXECUTE FUNCTION macro_position_reject_history_change();
"""
for table, name, columns, target, target_columns in SCOPED_CONSTRAINTS:
    GUARDS_SQL += f"""
ALTER TABLE {table} ADD CONSTRAINT {name} FOREIGN KEY {columns}
REFERENCES {target} {target_columns} DEFERRABLE INITIALLY IMMEDIATE;
"""

REVERSE_GUARDS_SQL = ""
for table, name, _, _, _ in reversed(SCOPED_CONSTRAINTS):
    REVERSE_GUARDS_SQL += f"ALTER TABLE {table} DROP CONSTRAINT {name};\n"
for table in reversed(IMMUTABLE_TABLES):
    REVERSE_GUARDS_SQL += f"DROP TRIGGER {table}_immutable ON {table};\n"
REVERSE_GUARDS_SQL += """
ALTER TABLE macro_paper_position_audit_transitions DROP CONSTRAINT macro_position_audit_detail_object;
ALTER TABLE macro_paper_position_command_receipts DROP CONSTRAINT macro_position_command_result_object;
ALTER TABLE macro_paper_position_versions DROP CONSTRAINT macro_position_quantity_bounds;
ALTER TABLE macro_paper_position_versions DROP CONSTRAINT macro_position_expiry_date;
DROP FUNCTION macro_position_is_date(text);
DROP TRIGGER macro_position_version_time_guard ON macro_paper_position_versions;
DROP FUNCTION macro_position_guard_version_time();
DROP TRIGGER macro_position_identity_progress_guard ON macro_paper_positions;
DROP FUNCTION macro_position_guard_identity_and_progress();
DROP FUNCTION macro_position_reject_history_change();
"""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('macro_theses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('changed_at', models.DateTimeField()),
                ('original_approval', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='original_paper_positions', to='macro_theses.approvalrecord')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='macro_paper_positions', to=settings.AUTH_USER_MODEL)),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paper_positions', to='macro_theses.thesisrecord')),
            ],
            options={
                'db_table': 'macro_paper_positions',
            },
        ),
        migrations.CreateModel(
            name='PositionVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('paper', models.BooleanField(default=True, editable=False)),
                ('status', models.CharField(choices=[('open', 'open'), ('closed', 'closed')], max_length=8)),
                ('mapping_status', models.CharField(default='user_declared_unverified', editable=False, max_length=32)),
                ('underlying', models.CharField(max_length=128)),
                ('direction', models.CharField(choices=[('long', 'long'), ('short', 'short')], max_length=8)),
                ('product_id', models.CharField(max_length=256, null=True)),
                ('venue', models.CharField(max_length=128, null=True)),
                ('expiry', models.CharField(max_length=10, null=True)),
                ('quote_currency', models.CharField(max_length=16, null=True)),
                ('horizon', models.CharField(max_length=1000, null=True)),
                ('quantity', models.CharField(max_length=29, null=True)),
                ('quantity_unit', models.CharField(max_length=64, null=True)),
                ('accepted_at', models.DateTimeField()),
                ('digest', models.CharField(max_length=64)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='macro_paper_position_versions', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='macro_positions.positionversion')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='macro_positions.positionrecord')),
                ('reviewed_approval', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_paper_position_versions', to='macro_theses.approvalrecord')),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paper_position_versions', to='macro_theses.thesisrecord')),
            ],
            options={
                'db_table': 'macro_paper_position_versions',
            },
        ),
        migrations.AddField(
            model_name='positionrecord',
            name='current_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='macro_positions.positionversion'),
        ),
        migrations.CreateModel(
            name='CommandReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_id', models.UUIDField()),
                ('kind', models.CharField(choices=[('create', 'create'), ('revise', 'revise'), ('close', 'close')], max_length=16)),
                ('request_digest', models.CharField(max_length=64)),
                ('result', models.JSONField()),
                ('saved_at', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='macro_paper_position_commands', to=settings.AUTH_USER_MODEL)),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paper_position_commands', to='macro_theses.thesisrecord')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='command_receipts', to='macro_positions.positionrecord')),
            ],
            options={
                'db_table': 'macro_paper_position_command_receipts',
                'constraints': [models.UniqueConstraint(fields=('owner', 'command_id'), name='macro_position_command_identity'), models.CheckConstraint(condition=models.Q(('kind__in', ('create', 'revise', 'close'))), name='macro_position_command_kind_allowed'), models.CheckConstraint(condition=models.Q(('request_digest__regex', '^[0-9a-f]{64}$')), name='macro_position_command_digest')],
            },
        ),
        migrations.CreateModel(
            name='AuditTransition',
            fields=[
                ('sequence', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=64)),
                ('at', models.DateTimeField()),
                ('detail', models.JSONField()),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paper_position_audit', to='macro_theses.thesisrecord')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_transitions', to='macro_positions.positionrecord')),
            ],
            options={
                'db_table': 'macro_paper_position_audit_transitions',
                'ordering': ('sequence',),
                'constraints': [models.CheckConstraint(condition=models.Q(('kind__regex', '\\S')), name='macro_position_audit_kind_named')],
            },
        ),
        migrations.AddConstraint(
            model_name='positionversion',
            constraint=models.UniqueConstraint(fields=('position', 'id'), name='macro_position_version_target'),
        ),
        migrations.AddConstraint(
            model_name='positionversion',
            constraint=models.CheckConstraint(condition=models.Q(('paper', True)), name='macro_position_paper_only'),
        ),
        migrations.AddConstraint(
            model_name='positionversion',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('open', 'closed'))), name='macro_position_status_allowed'),
        ),
        migrations.AddConstraint(
            model_name='positionversion',
            constraint=models.CheckConstraint(condition=models.Q(('mapping_status', 'user_declared_unverified')), name='macro_position_mapping_unverified'),
        ),
        migrations.AddConstraint(
            model_name='positionversion',
            constraint=models.CheckConstraint(condition=models.Q(('underlying__regex', '\\S')), name='macro_position_underlying_named'),
        ),
        migrations.AddConstraint(
            model_name='positionversion',
            constraint=models.CheckConstraint(condition=models.Q(('direction__in', ('long', 'short'))), name='macro_position_direction_allowed'),
        ),
        migrations.AddConstraint(
            model_name='positionversion',
            constraint=models.CheckConstraint(condition=models.Q(('digest__regex', '^[0-9a-f]{64}$')), name='macro_position_digest_sha256'),
        ),
        migrations.AddConstraint(
            model_name='positionversion',
            constraint=models.CheckConstraint(condition=models.Q(('parent', models.F('id')), _negated=True), name='macro_position_parent_not_self'),
        ),
        migrations.AddConstraint(
            model_name='positionversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('quantity__isnull', True), ('quantity_unit__isnull', True)), models.Q(('quantity__isnull', False), ('quantity_unit__isnull', False)), _connector='OR'), name='macro_position_quantity_unit_pair'),
        ),
        migrations.AddConstraint(
            model_name='positionversion',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__regex', '^(0|[1-9][0-9]*)(\\.[0-9]+)?$')), name='macro_position_quantity_lexical'),
        ),
        migrations.AddConstraint(
            model_name='positionversion',
            constraint=models.CheckConstraint(condition=models.Q(('product_id__regex', '\\S')), name='macro_position_product_id_named'),
        ),
        migrations.AddConstraint(
            model_name='positionversion',
            constraint=models.CheckConstraint(condition=models.Q(('venue__regex', '\\S')), name='macro_position_venue_named'),
        ),
        migrations.AddConstraint(
            model_name='positionversion',
            constraint=models.CheckConstraint(condition=models.Q(('quote_currency__regex', '\\S')), name='macro_position_quote_currency_named'),
        ),
        migrations.AddConstraint(
            model_name='positionversion',
            constraint=models.CheckConstraint(condition=models.Q(('horizon__regex', '\\S')), name='macro_position_horizon_named'),
        ),
        migrations.AddConstraint(
            model_name='positionversion',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_unit__regex', '\\S')), name='macro_position_quantity_unit_named'),
        ),
        migrations.AddConstraint(
            model_name='positionrecord',
            constraint=models.UniqueConstraint(fields=('id', 'thesis'), name='macro_position_thesis_target'),
        ),
        migrations.AddConstraint(
            model_name='positionrecord',
            constraint=models.UniqueConstraint(fields=('id', 'thesis', 'owner'), name='macro_position_scope_target'),
        ),
        migrations.AddConstraint(
            model_name='positionrecord',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 0)), name='macro_position_revision_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='positionrecord',
            constraint=models.CheckConstraint(condition=models.Q(('changed_at__gte', models.F('created_at'))), name='macro_position_time_order'),
        ),
        migrations.AddConstraint(
            model_name='positionrecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('current_version__isnull', True), ('revision', 0)), models.Q(('current_version__isnull', False), ('revision__gt', 0)), _connector='OR'), name='macro_position_current_revision_pair'),
        ),
        migrations.RunSQL(sql=GUARDS_SQL, reverse_sql=REVERSE_GUARDS_SQL),
    ]
