BEGIN;
--
-- Create model PositionRecord
--
CREATE TABLE "macro_paper_positions" ("id" uuid NOT NULL PRIMARY KEY, "revision" bigint NOT NULL CHECK ("revision" >= 0), "created_at" timestamp with time zone NOT NULL, "changed_at" timestamp with time zone NOT NULL, "original_approval_id" uuid NOT NULL, "owner_id" uuid NOT NULL, "thesis_id" uuid NOT NULL);
--
-- Create model PositionVersion
--
CREATE TABLE "macro_paper_position_versions" ("id" uuid NOT NULL PRIMARY KEY, "paper" boolean NOT NULL, "status" varchar(8) NOT NULL, "mapping_status" varchar(32) NOT NULL, "underlying" varchar(128) NOT NULL, "direction" varchar(8) NOT NULL, "product_id" varchar(256) NULL, "venue" varchar(128) NULL, "expiry" varchar(10) NULL, "quote_currency" varchar(16) NULL, "horizon" varchar(1000) NULL, "quantity" varchar(29) NULL, "quantity_unit" varchar(64) NULL, "accepted_at" timestamp with time zone NOT NULL, "digest" varchar(64) NOT NULL, "owner_id" uuid NOT NULL, "parent_id" uuid NULL, "position_id" uuid NOT NULL, "reviewed_approval_id" uuid NOT NULL, "thesis_id" uuid NOT NULL);
--
-- Add field current_version to positionrecord
--
ALTER TABLE "macro_paper_positions" ADD COLUMN "current_version_id" uuid NULL CONSTRAINT "macro_paper_position_current_version_id_db5d6e64_fk_macro_pap" REFERENCES "macro_paper_position_versions"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "macro_paper_position_current_version_id_db5d6e64_fk_macro_pap" IMMEDIATE;
--
-- Create model CommandReceipt
--
CREATE TABLE "macro_paper_position_command_receipts" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "command_id" uuid NOT NULL, "kind" varchar(16) NOT NULL, "request_digest" varchar(64) NOT NULL, "result" jsonb NOT NULL, "saved_at" timestamp with time zone NOT NULL, "owner_id" uuid NOT NULL, "thesis_id" uuid NOT NULL, "position_id" uuid NOT NULL, CONSTRAINT "macro_position_command_identity" UNIQUE ("owner_id", "command_id"), CONSTRAINT "macro_position_command_kind_allowed" CHECK ("kind" IN ('create', 'revise', 'close')), CONSTRAINT "macro_position_command_digest" CHECK ("request_digest"::text ~ '^[0-9a-f]{64}$'));
--
-- Create model AuditTransition
--
CREATE TABLE "macro_paper_position_audit_transitions" ("sequence" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "kind" varchar(64) NOT NULL, "at" timestamp with time zone NOT NULL, "detail" jsonb NOT NULL, "thesis_id" uuid NOT NULL, "position_id" uuid NOT NULL, CONSTRAINT "macro_position_audit_kind_named" CHECK ("kind"::text ~  E'\\S'));
--
-- Create constraint macro_position_version_target on model positionversion
--
ALTER TABLE "macro_paper_position_versions" ADD CONSTRAINT "macro_position_version_target" UNIQUE ("position_id", "id");
--
-- Create constraint macro_position_paper_only on model positionversion
--
ALTER TABLE "macro_paper_position_versions" ADD CONSTRAINT "macro_position_paper_only" CHECK ("paper");
--
-- Create constraint macro_position_status_allowed on model positionversion
--
ALTER TABLE "macro_paper_position_versions" ADD CONSTRAINT "macro_position_status_allowed" CHECK ("status" IN ('open', 'closed'));
--
-- Create constraint macro_position_mapping_unverified on model positionversion
--
ALTER TABLE "macro_paper_position_versions" ADD CONSTRAINT "macro_position_mapping_unverified" CHECK ("mapping_status" = 'user_declared_unverified');
--
-- Create constraint macro_position_underlying_named on model positionversion
--
ALTER TABLE "macro_paper_position_versions" ADD CONSTRAINT "macro_position_underlying_named" CHECK ("underlying"::text ~  E'\\S');
--
-- Create constraint macro_position_direction_allowed on model positionversion
--
ALTER TABLE "macro_paper_position_versions" ADD CONSTRAINT "macro_position_direction_allowed" CHECK ("direction" IN ('long', 'short'));
--
-- Create constraint macro_position_digest_sha256 on model positionversion
--
ALTER TABLE "macro_paper_position_versions" ADD CONSTRAINT "macro_position_digest_sha256" CHECK ("digest"::text ~ '^[0-9a-f]{64}$');
--
-- Create constraint macro_position_parent_not_self on model positionversion
--
ALTER TABLE "macro_paper_position_versions" ADD CONSTRAINT "macro_position_parent_not_self" CHECK (NOT ("parent_id" = ("id") AND "parent_id" IS NOT NULL));
--
-- Create constraint macro_position_quantity_unit_pair on model positionversion
--
ALTER TABLE "macro_paper_position_versions" ADD CONSTRAINT "macro_position_quantity_unit_pair" CHECK ((("quantity" IS NULL AND "quantity_unit" IS NULL) OR ("quantity" IS NOT NULL AND "quantity_unit" IS NOT NULL)));
--
-- Create constraint macro_position_quantity_lexical on model positionversion
--
ALTER TABLE "macro_paper_position_versions" ADD CONSTRAINT "macro_position_quantity_lexical" CHECK ("quantity"::text ~  E'^(0|[1-9][0-9]*)(\\.[0-9]+)?$');
--
-- Create constraint macro_position_product_id_named on model positionversion
--
ALTER TABLE "macro_paper_position_versions" ADD CONSTRAINT "macro_position_product_id_named" CHECK ("product_id"::text ~  E'\\S');
--
-- Create constraint macro_position_venue_named on model positionversion
--
ALTER TABLE "macro_paper_position_versions" ADD CONSTRAINT "macro_position_venue_named" CHECK ("venue"::text ~  E'\\S');
--
-- Create constraint macro_position_quote_currency_named on model positionversion
--
ALTER TABLE "macro_paper_position_versions" ADD CONSTRAINT "macro_position_quote_currency_named" CHECK ("quote_currency"::text ~  E'\\S');
--
-- Create constraint macro_position_horizon_named on model positionversion
--
ALTER TABLE "macro_paper_position_versions" ADD CONSTRAINT "macro_position_horizon_named" CHECK ("horizon"::text ~  E'\\S');
--
-- Create constraint macro_position_quantity_unit_named on model positionversion
--
ALTER TABLE "macro_paper_position_versions" ADD CONSTRAINT "macro_position_quantity_unit_named" CHECK ("quantity_unit"::text ~  E'\\S');
--
-- Create constraint macro_position_thesis_target on model positionrecord
--
ALTER TABLE "macro_paper_positions" ADD CONSTRAINT "macro_position_thesis_target" UNIQUE ("id", "thesis_id");
--
-- Create constraint macro_position_scope_target on model positionrecord
--
ALTER TABLE "macro_paper_positions" ADD CONSTRAINT "macro_position_scope_target" UNIQUE ("id", "thesis_id", "owner_id");
--
-- Create constraint macro_position_revision_nonnegative on model positionrecord
--
ALTER TABLE "macro_paper_positions" ADD CONSTRAINT "macro_position_revision_nonnegative" CHECK ("revision" >= 0);
--
-- Create constraint macro_position_time_order on model positionrecord
--
ALTER TABLE "macro_paper_positions" ADD CONSTRAINT "macro_position_time_order" CHECK ("changed_at" >= ("created_at"));
--
-- Create constraint macro_position_current_revision_pair on model positionrecord
--
ALTER TABLE "macro_paper_positions" ADD CONSTRAINT "macro_position_current_revision_pair" CHECK ((("current_version_id" IS NULL AND "revision" = 0) OR ("current_version_id" IS NOT NULL AND "revision" > 0)));
--
-- Raw SQL operation
--

CREATE FUNCTION macro_position_reject_history_change() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'immutable paper position history: %', TG_TABLE_NAME USING ERRCODE = '23514';
END;
$$;

CREATE FUNCTION macro_position_guard_identity_and_progress() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    proposed macro_paper_position_versions%ROWTYPE;
    previous macro_paper_position_versions%ROWTYPE;
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'durable paper position cannot be deleted' USING ERRCODE = '23514';
    END IF;
    IF ROW(NEW.id, NEW.owner_id, NEW.thesis_id, NEW.original_approval_id, NEW.created_at)
       IS DISTINCT FROM ROW(OLD.id, OLD.owner_id, OLD.thesis_id, OLD.original_approval_id, OLD.created_at) THEN
        RAISE EXCEPTION 'paper position identity, scope, and original approval are immutable'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.changed_at < OLD.changed_at THEN
        RAISE EXCEPTION 'position changed_at cannot move backwards' USING ERRCODE = '23514';
    END IF;
    IF NEW.current_version_id IS DISTINCT FROM OLD.current_version_id THEN
        IF NEW.revision <> OLD.revision + 1 THEN
            RAISE EXCEPTION 'a new position version requires the next aggregate revision'
                USING ERRCODE = '23514';
        END IF;
        SELECT * INTO proposed FROM macro_paper_position_versions WHERE id = NEW.current_version_id;
        IF NOT FOUND THEN
            RAISE EXCEPTION 'position version does not exist' USING ERRCODE = '23503';
        END IF;
        IF proposed.position_id <> NEW.id OR proposed.parent_id IS DISTINCT FROM OLD.current_version_id
           OR proposed.accepted_at IS DISTINCT FROM NEW.changed_at THEN
            RAISE EXCEPTION 'current version must preserve scope, parent, and effective time'
                USING ERRCODE = '23514';
        END IF;
        IF OLD.current_version_id IS NULL THEN
            IF proposed.status <> 'open' OR proposed.reviewed_approval_id <> NEW.original_approval_id THEN
                RAISE EXCEPTION 'an initial position must be open and use its original approval'
                    USING ERRCODE = '23514';
            END IF;
        ELSE
            SELECT * INTO previous FROM macro_paper_position_versions WHERE id = OLD.current_version_id;
            IF previous.status = 'closed' THEN
                RAISE EXCEPTION 'a closed paper position cannot be revised or reopened'
                    USING ERRCODE = '23514';
            END IF;
            IF proposed.status = 'closed' AND ROW(
                proposed.underlying, proposed.direction, proposed.product_id, proposed.venue,
                proposed.expiry, proposed.quote_currency, proposed.horizon, proposed.quantity,
                proposed.quantity_unit
            ) IS DISTINCT FROM ROW(
                previous.underlying, previous.direction, previous.product_id, previous.venue,
                previous.expiry, previous.quote_currency, previous.horizon, previous.quantity,
                previous.quantity_unit
            ) THEN
                RAISE EXCEPTION 'closing a position cannot revise exposure declarations'
                    USING ERRCODE = '23514';
            END IF;
        END IF;
    ELSIF NEW.revision <> OLD.revision OR NEW.changed_at IS DISTINCT FROM OLD.changed_at THEN
        RAISE EXCEPTION 'position progress requires a new immutable version' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER macro_position_identity_progress_guard
BEFORE UPDATE OR DELETE ON macro_paper_positions
FOR EACH ROW EXECUTE FUNCTION macro_position_guard_identity_and_progress();

CREATE FUNCTION macro_position_guard_version_time() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    created timestamptz;
    approved timestamptz;
    parent_time timestamptz;
    parent_status text;
BEGIN
    SELECT created_at INTO created FROM macro_paper_positions WHERE id = NEW.position_id;
    SELECT approved_at INTO approved FROM macro_thesis_approvals WHERE id = NEW.reviewed_approval_id;
    IF NEW.accepted_at < created OR NEW.accepted_at < approved THEN
        RAISE EXCEPTION 'position version cannot predate position or reviewed approval'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.parent_id IS NOT NULL THEN
        SELECT accepted_at, status INTO parent_time, parent_status
            FROM macro_paper_position_versions WHERE id = NEW.parent_id;
        IF NEW.accepted_at < parent_time OR parent_status = 'closed' THEN
            RAISE EXCEPTION 'position version cannot predate or follow a closed parent'
                USING ERRCODE = '23514';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER macro_position_version_time_guard
BEFORE INSERT ON macro_paper_position_versions
FOR EACH ROW EXECUTE FUNCTION macro_position_guard_version_time();

CREATE FUNCTION macro_position_is_date(value text) RETURNS boolean
LANGUAGE plpgsql IMMUTABLE STRICT AS $$
BEGIN
    IF value !~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' THEN
        RETURN FALSE;
    END IF;
    PERFORM make_date(substring(value, 1, 4)::integer, substring(value, 6, 2)::integer,
                      substring(value, 9, 2)::integer);
    RETURN TRUE;
EXCEPTION WHEN datetime_field_overflow THEN
    RETURN FALSE;
END;
$$;
ALTER TABLE macro_paper_position_versions ADD CONSTRAINT macro_position_expiry_date
    CHECK (macro_position_is_date(expiry));
ALTER TABLE macro_paper_position_versions ADD CONSTRAINT macro_position_quantity_bounds
    CHECK (CASE WHEN quantity ~ '^(0|[1-9][0-9]*)(\.[0-9]+)?$' THEN
        quantity::numeric > 0
        AND length(replace(quantity, '.', '')) <= 28
        AND length(split_part(quantity, '.', 2)) <= 12
    ELSE quantity IS NULL END);
ALTER TABLE macro_paper_position_command_receipts ADD CONSTRAINT macro_position_command_result_object
    CHECK (jsonb_typeof(result) = 'object');
ALTER TABLE macro_paper_position_audit_transitions ADD CONSTRAINT macro_position_audit_detail_object
    CHECK (jsonb_typeof(detail) = 'object');

CREATE TRIGGER macro_paper_position_versions_immutable BEFORE UPDATE OR DELETE ON macro_paper_position_versions
FOR EACH ROW EXECUTE FUNCTION macro_position_reject_history_change();

CREATE TRIGGER macro_paper_position_command_receipts_immutable BEFORE UPDATE OR DELETE ON macro_paper_position_command_receipts
FOR EACH ROW EXECUTE FUNCTION macro_position_reject_history_change();

CREATE TRIGGER macro_paper_position_audit_transitions_immutable BEFORE UPDATE OR DELETE ON macro_paper_position_audit_transitions
FOR EACH ROW EXECUTE FUNCTION macro_position_reject_history_change();

ALTER TABLE macro_paper_positions ADD CONSTRAINT macro_position_owner_scope_fk FOREIGN KEY (thesis_id, owner_id)
REFERENCES macro_theses (id, owner_id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE macro_paper_positions ADD CONSTRAINT macro_position_original_approval_fk FOREIGN KEY (thesis_id, original_approval_id)
REFERENCES macro_thesis_approvals (thesis_id, id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE macro_paper_position_versions ADD CONSTRAINT macro_position_version_scope_fk FOREIGN KEY (position_id, thesis_id, owner_id)
REFERENCES macro_paper_positions (id, thesis_id, owner_id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE macro_paper_position_versions ADD CONSTRAINT macro_position_reviewed_approval_fk FOREIGN KEY (thesis_id, reviewed_approval_id)
REFERENCES macro_thesis_approvals (thesis_id, id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE macro_paper_position_versions ADD CONSTRAINT macro_position_parent_scope_fk FOREIGN KEY (position_id, parent_id)
REFERENCES macro_paper_position_versions (position_id, id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE macro_paper_positions ADD CONSTRAINT macro_position_current_scope_fk FOREIGN KEY (id, current_version_id)
REFERENCES macro_paper_position_versions (position_id, id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE macro_paper_position_command_receipts ADD CONSTRAINT macro_position_command_scope_fk FOREIGN KEY (position_id, thesis_id, owner_id)
REFERENCES macro_paper_positions (id, thesis_id, owner_id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE macro_paper_position_audit_transitions ADD CONSTRAINT macro_position_audit_scope_fk FOREIGN KEY (position_id, thesis_id)
REFERENCES macro_paper_positions (id, thesis_id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "macro_paper_positions" ADD CONSTRAINT "macro_paper_position_original_approval_id_e6cd10d9_fk_macro_the" FOREIGN KEY ("original_approval_id") REFERENCES "macro_thesis_approvals" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "macro_paper_positions" ADD CONSTRAINT "macro_paper_positions_owner_id_cee1a4f7_fk_macro_web_user_id" FOREIGN KEY ("owner_id") REFERENCES "macro_web_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "macro_paper_positions" ADD CONSTRAINT "macro_paper_positions_thesis_id_18785452_fk_macro_theses_id" FOREIGN KEY ("thesis_id") REFERENCES "macro_theses" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "macro_paper_positions_original_approval_id_e6cd10d9" ON "macro_paper_positions" ("original_approval_id");
CREATE INDEX "macro_paper_positions_owner_id_cee1a4f7" ON "macro_paper_positions" ("owner_id");
CREATE INDEX "macro_paper_positions_thesis_id_18785452" ON "macro_paper_positions" ("thesis_id");
ALTER TABLE "macro_paper_position_versions" ADD CONSTRAINT "macro_paper_position_owner_id_6372f7d9_fk_macro_web" FOREIGN KEY ("owner_id") REFERENCES "macro_web_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "macro_paper_position_versions" ADD CONSTRAINT "macro_paper_position_parent_id_4002fd87_fk_macro_pap" FOREIGN KEY ("parent_id") REFERENCES "macro_paper_position_versions" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "macro_paper_position_versions" ADD CONSTRAINT "macro_paper_position_position_id_4cc5d994_fk_macro_pap" FOREIGN KEY ("position_id") REFERENCES "macro_paper_positions" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "macro_paper_position_versions" ADD CONSTRAINT "macro_paper_position_reviewed_approval_id_8e1efcb4_fk_macro_the" FOREIGN KEY ("reviewed_approval_id") REFERENCES "macro_thesis_approvals" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "macro_paper_position_versions" ADD CONSTRAINT "macro_paper_position_thesis_id_c8e72f64_fk_macro_the" FOREIGN KEY ("thesis_id") REFERENCES "macro_theses" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "macro_paper_position_versions_owner_id_6372f7d9" ON "macro_paper_position_versions" ("owner_id");
CREATE INDEX "macro_paper_position_versions_parent_id_4002fd87" ON "macro_paper_position_versions" ("parent_id");
CREATE INDEX "macro_paper_position_versions_position_id_4cc5d994" ON "macro_paper_position_versions" ("position_id");
CREATE INDEX "macro_paper_position_versions_reviewed_approval_id_8e1efcb4" ON "macro_paper_position_versions" ("reviewed_approval_id");
CREATE INDEX "macro_paper_position_versions_thesis_id_c8e72f64" ON "macro_paper_position_versions" ("thesis_id");
CREATE INDEX "macro_paper_positions_current_version_id_db5d6e64" ON "macro_paper_positions" ("current_version_id");
ALTER TABLE "macro_paper_position_command_receipts" ADD CONSTRAINT "macro_paper_position_owner_id_90641c13_fk_macro_web" FOREIGN KEY ("owner_id") REFERENCES "macro_web_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "macro_paper_position_command_receipts" ADD CONSTRAINT "macro_paper_position_thesis_id_cf7d25c7_fk_macro_the" FOREIGN KEY ("thesis_id") REFERENCES "macro_theses" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "macro_paper_position_command_receipts" ADD CONSTRAINT "macro_paper_position_position_id_0dd5fbe7_fk_macro_pap" FOREIGN KEY ("position_id") REFERENCES "macro_paper_positions" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "macro_paper_position_command_receipts_owner_id_90641c13" ON "macro_paper_position_command_receipts" ("owner_id");
CREATE INDEX "macro_paper_position_command_receipts_thesis_id_cf7d25c7" ON "macro_paper_position_command_receipts" ("thesis_id");
CREATE INDEX "macro_paper_position_command_receipts_position_id_0dd5fbe7" ON "macro_paper_position_command_receipts" ("position_id");
ALTER TABLE "macro_paper_position_audit_transitions" ADD CONSTRAINT "macro_paper_position_thesis_id_1977e697_fk_macro_the" FOREIGN KEY ("thesis_id") REFERENCES "macro_theses" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "macro_paper_position_audit_transitions" ADD CONSTRAINT "macro_paper_position_position_id_ae7aac34_fk_macro_pap" FOREIGN KEY ("position_id") REFERENCES "macro_paper_positions" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "macro_paper_position_audit_transitions_thesis_id_1977e697" ON "macro_paper_position_audit_transitions" ("thesis_id");
CREATE INDEX "macro_paper_position_audit_transitions_position_id_ae7aac34" ON "macro_paper_position_audit_transitions" ("position_id");
COMMIT;
