BEGIN;
--
-- Create model BriefStateRecord
--
CREATE TABLE "macro_brief_states" ("brief_id" varchar(255) NOT NULL PRIMARY KEY, "generation" bigint NOT NULL CHECK ("generation" >= 0), "changed_at" timestamp with time zone NOT NULL, "owner_id" uuid NOT NULL, CONSTRAINT "macro_brief_id_named" CHECK ("brief_id"::text ~  E'\\S'), CONSTRAINT "macro_brief_generation_nonnegative" CHECK ("generation" >= 0));
--
-- Create model DependencyVersion
--
CREATE TABLE "macro_dependency_versions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "role" varchar(64) NOT NULL, "version_id" varchar(512) NOT NULL, "digest" varchar(64) NOT NULL, "known_at" timestamp with time zone NOT NULL, "brief_id" varchar(255) NOT NULL, CONSTRAINT "macro_dependency_version_identity" UNIQUE ("brief_id", "role", "version_id"), CONSTRAINT "macro_dependency_scoped_target" UNIQUE ("brief_id", "role", "id"), CONSTRAINT "macro_dependency_role_allowed" CHECK ("role" IN ('activation', 'budget', 'compiled_thesis', 'coverage', 'entitlements', 'event_revision', 'execution_graph', 'exposure', 'knowledge', 'macro_context', 'model', 'prompt', 'rules', 'source_contract', 'source_manifest', 'user_thesis')), CONSTRAINT "macro_dependency_version_named" CHECK ("version_id"::text ~  E'\\S'), CONSTRAINT "macro_dependency_digest_sha256" CHECK ("digest"::text ~ '^[0-9a-f]{64}$'));
--
-- Create model DependencyHead
--
CREATE TABLE "macro_dependency_heads" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "role" varchar(64) NOT NULL, "brief_id" varchar(255) NOT NULL, "version_id" bigint NOT NULL, CONSTRAINT "macro_dependency_head_identity" UNIQUE ("brief_id", "role"), CONSTRAINT "macro_dependency_head_role_allowed" CHECK ("role" IN ('activation', 'budget', 'compiled_thesis', 'coverage', 'entitlements', 'event_revision', 'execution_graph', 'exposure', 'knowledge', 'macro_context', 'model', 'prompt', 'rules', 'source_contract', 'source_manifest', 'user_thesis')));
--
-- Create model AssessmentRecord
--
CREATE TABLE "macro_assessments" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "assessment_id" varchar(255) NOT NULL, "digest" varchar(64) NOT NULL, "payload" text NOT NULL, "status" varchar(16) NOT NULL, "reasons" jsonb NOT NULL, "reassessment_required" boolean NOT NULL, "observed_dependencies" jsonb NOT NULL, "saved_at" timestamp with time zone NOT NULL, "brief_id" varchar(255) NOT NULL, CONSTRAINT "macro_assessment_identity" UNIQUE ("brief_id", "assessment_id"), CONSTRAINT "macro_assessment_scoped_target" UNIQUE ("brief_id", "id"), CONSTRAINT "macro_assessment_id_named" CHECK ("assessment_id"::text ~  E'\\S'), CONSTRAINT "macro_assessment_digest_sha256" CHECK ("digest"::text ~ '^[0-9a-f]{64}$'), CONSTRAINT "macro_assessment_status_allowed" CHECK ("status" IN ('current', 'superseded')));
--
-- Create model CurrentAssessment
--
CREATE TABLE "macro_current_assessments" ("brief_id" varchar(255) NOT NULL PRIMARY KEY, "assessment_id" bigint NOT NULL);
--
-- Create model BriefVersion
--
CREATE TABLE "macro_brief_versions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "generation" bigint NOT NULL CHECK ("generation" >= 0), "saved_at" timestamp with time zone NOT NULL, "brief_id" varchar(255) NOT NULL, "assessment_id" bigint NOT NULL, CONSTRAINT "macro_brief_version_generation" UNIQUE ("brief_id", "generation"), CONSTRAINT "macro_brief_version_generation_positive" CHECK ("generation" > 0));
--
-- Create model NotificationIntent
--
CREATE TABLE "macro_notification_intents" ("intent_id" varchar(80) NOT NULL PRIMARY KEY, "state" varchar(16) NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "brief_id" varchar(255) NOT NULL, "assessment_id" bigint NOT NULL, CONSTRAINT "macro_notification_id_named" CHECK ("intent_id"::text ~  E'\\S'), CONSTRAINT "macro_notification_state_allowed" CHECK ("state" IN ('pending', 'canceled', 'delivered')), CONSTRAINT "macro_notification_time_order" CHECK ("updated_at" >= ("created_at")));
--
-- Create model ReassessmentWork
--
CREATE TABLE "macro_reassessment_work" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "context_digest" varchar(64) NOT NULL, "reason" text NOT NULL, "created_at" timestamp with time zone NOT NULL, "state" varchar(16) NOT NULL, "completed_at" timestamp with time zone NULL, "brief_id" varchar(255) NOT NULL, CONSTRAINT "macro_reassessment_context_identity" UNIQUE ("brief_id", "context_digest"), CONSTRAINT "macro_reassessment_digest_sha256" CHECK ("context_digest"::text ~ '^[0-9a-f]{64}$'), CONSTRAINT "macro_reassessment_reason_named" CHECK ("reason"::text ~  E'\\S'), CONSTRAINT "macro_reassessment_completion_state" CHECK ((("completed_at" IS NULL AND "state" = 'pending') OR ("completed_at" >= ("created_at") AND "completed_at" IS NOT NULL AND "state" IN ('completed', 'superseded')))));
--
-- Create model AuditTransition
--
CREATE TABLE "macro_audit_transitions" ("sequence" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "kind" varchar(64) NOT NULL, "happened_at" timestamp with time zone NOT NULL, "detail" jsonb NOT NULL, "brief_id" varchar(255) NOT NULL, CONSTRAINT "macro_audit_kind_named" CHECK ("kind"::text ~  E'\\S'));
--
-- Raw SQL operation
--

CREATE FUNCTION macro_agent_reject_history_change() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'immutable history: %', TG_TABLE_NAME USING ERRCODE = '23514';
END;
$$;
CREATE FUNCTION macro_agent_protect_brief_identity() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.brief_id IS DISTINCT FROM OLD.brief_id
       OR NEW.owner_id IS DISTINCT FROM OLD.owner_id THEN
        RAISE EXCEPTION 'brief identity and owner are immutable' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER macro_brief_identity_guard BEFORE UPDATE ON macro_brief_states
FOR EACH ROW EXECUTE FUNCTION macro_agent_protect_brief_identity();
ALTER TABLE macro_assessments ADD CONSTRAINT macro_assessment_payload_object
    CHECK (jsonb_typeof(payload::jsonb) = 'object');
ALTER TABLE macro_assessments ADD CONSTRAINT macro_assessment_reasons_array
    CHECK (jsonb_typeof(reasons) = 'array');
ALTER TABLE macro_assessments ADD CONSTRAINT macro_assessment_observed_array
    CHECK (jsonb_typeof(observed_dependencies) = 'array');
ALTER TABLE macro_audit_transitions ADD CONSTRAINT macro_audit_detail_object
    CHECK (jsonb_typeof(detail) = 'object');

CREATE TRIGGER macro_dependency_versions_immutable BEFORE UPDATE OR DELETE ON macro_dependency_versions
FOR EACH ROW EXECUTE FUNCTION macro_agent_reject_history_change();

CREATE TRIGGER macro_assessments_immutable BEFORE UPDATE OR DELETE ON macro_assessments
FOR EACH ROW EXECUTE FUNCTION macro_agent_reject_history_change();

CREATE TRIGGER macro_brief_versions_immutable BEFORE UPDATE OR DELETE ON macro_brief_versions
FOR EACH ROW EXECUTE FUNCTION macro_agent_reject_history_change();

CREATE TRIGGER macro_audit_transitions_immutable BEFORE UPDATE OR DELETE ON macro_audit_transitions
FOR EACH ROW EXECUTE FUNCTION macro_agent_reject_history_change();

ALTER TABLE macro_dependency_heads ADD CONSTRAINT macro_head_scoped_version_fk FOREIGN KEY (brief_id, role, version_id)
REFERENCES macro_dependency_versions (brief_id, role, id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE macro_current_assessments ADD CONSTRAINT macro_current_scoped_assessment_fk FOREIGN KEY (brief_id, assessment_id)
REFERENCES macro_assessments (brief_id, id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE macro_brief_versions ADD CONSTRAINT macro_version_scoped_assessment_fk FOREIGN KEY (brief_id, assessment_id)
REFERENCES macro_assessments (brief_id, id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE macro_notification_intents ADD CONSTRAINT macro_notice_scoped_assessment_fk FOREIGN KEY (brief_id, assessment_id)
REFERENCES macro_assessments (brief_id, id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "macro_brief_states" ADD CONSTRAINT "macro_brief_states_owner_id_16eded4f_fk_macro_web_user_id" FOREIGN KEY ("owner_id") REFERENCES "macro_web_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "macro_brief_states_brief_id_ccf96a50_like" ON "macro_brief_states" ("brief_id" varchar_pattern_ops);
CREATE INDEX "macro_brief_states_owner_id_16eded4f" ON "macro_brief_states" ("owner_id");
ALTER TABLE "macro_dependency_versions" ADD CONSTRAINT "macro_dependency_ver_brief_id_90b05251_fk_macro_bri" FOREIGN KEY ("brief_id") REFERENCES "macro_brief_states" ("brief_id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "macro_dependency_versions_brief_id_90b05251" ON "macro_dependency_versions" ("brief_id");
CREATE INDEX "macro_dependency_versions_brief_id_90b05251_like" ON "macro_dependency_versions" ("brief_id" varchar_pattern_ops);
ALTER TABLE "macro_dependency_heads" ADD CONSTRAINT "macro_dependency_hea_brief_id_ce647bd5_fk_macro_bri" FOREIGN KEY ("brief_id") REFERENCES "macro_brief_states" ("brief_id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "macro_dependency_heads" ADD CONSTRAINT "macro_dependency_hea_version_id_d3e7ca58_fk_macro_dep" FOREIGN KEY ("version_id") REFERENCES "macro_dependency_versions" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "macro_dependency_heads_brief_id_ce647bd5" ON "macro_dependency_heads" ("brief_id");
CREATE INDEX "macro_dependency_heads_brief_id_ce647bd5_like" ON "macro_dependency_heads" ("brief_id" varchar_pattern_ops);
CREATE INDEX "macro_dependency_heads_version_id_d3e7ca58" ON "macro_dependency_heads" ("version_id");
ALTER TABLE "macro_assessments" ADD CONSTRAINT "macro_assessments_brief_id_3a405b1a_fk_macro_bri" FOREIGN KEY ("brief_id") REFERENCES "macro_brief_states" ("brief_id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "macro_assessments_brief_id_3a405b1a" ON "macro_assessments" ("brief_id");
CREATE INDEX "macro_assessments_brief_id_3a405b1a_like" ON "macro_assessments" ("brief_id" varchar_pattern_ops);
ALTER TABLE "macro_current_assessments" ADD CONSTRAINT "macro_current_assess_brief_id_89db10bf_fk_macro_bri" FOREIGN KEY ("brief_id") REFERENCES "macro_brief_states" ("brief_id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "macro_current_assessments" ADD CONSTRAINT "macro_current_assess_assessment_id_8b501148_fk_macro_ass" FOREIGN KEY ("assessment_id") REFERENCES "macro_assessments" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "macro_current_assessments_brief_id_89db10bf_like" ON "macro_current_assessments" ("brief_id" varchar_pattern_ops);
CREATE INDEX "macro_current_assessments_assessment_id_8b501148" ON "macro_current_assessments" ("assessment_id");
ALTER TABLE "macro_brief_versions" ADD CONSTRAINT "macro_brief_versions_brief_id_a920686c_fk_macro_bri" FOREIGN KEY ("brief_id") REFERENCES "macro_brief_states" ("brief_id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "macro_brief_versions" ADD CONSTRAINT "macro_brief_versions_assessment_id_7e9ef253_fk_macro_ass" FOREIGN KEY ("assessment_id") REFERENCES "macro_assessments" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "macro_brief_versions_brief_id_a920686c" ON "macro_brief_versions" ("brief_id");
CREATE INDEX "macro_brief_versions_brief_id_a920686c_like" ON "macro_brief_versions" ("brief_id" varchar_pattern_ops);
CREATE INDEX "macro_brief_versions_assessment_id_7e9ef253" ON "macro_brief_versions" ("assessment_id");
ALTER TABLE "macro_notification_intents" ADD CONSTRAINT "macro_notification_i_brief_id_af777b69_fk_macro_bri" FOREIGN KEY ("brief_id") REFERENCES "macro_brief_states" ("brief_id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "macro_notification_intents" ADD CONSTRAINT "macro_notification_i_assessment_id_72e6b021_fk_macro_ass" FOREIGN KEY ("assessment_id") REFERENCES "macro_assessments" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "macro_notification_intents_intent_id_582e8561_like" ON "macro_notification_intents" ("intent_id" varchar_pattern_ops);
CREATE INDEX "macro_notification_intents_brief_id_af777b69" ON "macro_notification_intents" ("brief_id");
CREATE INDEX "macro_notification_intents_brief_id_af777b69_like" ON "macro_notification_intents" ("brief_id" varchar_pattern_ops);
CREATE INDEX "macro_notification_intents_assessment_id_72e6b021" ON "macro_notification_intents" ("assessment_id");
CREATE INDEX "macro_notification_pending_idx" ON "macro_notification_intents" ("brief_id", "state");
ALTER TABLE "macro_reassessment_work" ADD CONSTRAINT "macro_reassessment_w_brief_id_8c042c3e_fk_macro_bri" FOREIGN KEY ("brief_id") REFERENCES "macro_brief_states" ("brief_id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "macro_reassessment_work_brief_id_8c042c3e" ON "macro_reassessment_work" ("brief_id");
CREATE INDEX "macro_reassessment_work_brief_id_8c042c3e_like" ON "macro_reassessment_work" ("brief_id" varchar_pattern_ops);
ALTER TABLE "macro_audit_transitions" ADD CONSTRAINT "macro_audit_transiti_brief_id_eba9c72a_fk_macro_bri" FOREIGN KEY ("brief_id") REFERENCES "macro_brief_states" ("brief_id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "macro_audit_transitions_brief_id_eba9c72a" ON "macro_audit_transitions" ("brief_id");
CREATE INDEX "macro_audit_transitions_brief_id_eba9c72a_like" ON "macro_audit_transitions" ("brief_id" varchar_pattern_ops);
COMMIT;
