BEGIN;
--
-- Create model TextVersionRecord
--
CREATE TABLE "macro_thesis_text_versions" ("id" uuid NOT NULL PRIMARY KEY, "exact_text" text NOT NULL, "text_digest" varchar(64) NOT NULL, "created_at" timestamp with time zone NOT NULL, "parent_id" uuid NULL);
--
-- Create model InterpretationRecord
--
CREATE TABLE "macro_thesis_interpretations" ("id" uuid NOT NULL PRIMARY KEY, "drivers" jsonb NOT NULL, "horizon" text NULL, "invalidation_signposts" jsonb NOT NULL, "known_at" timestamp with time zone NOT NULL, "digest" varchar(64) NOT NULL, "origin" varchar(32) NOT NULL, "text_version_id" uuid NOT NULL);
--
-- Create model ApprovalRecord
--
CREATE TABLE "macro_thesis_approvals" ("id" uuid NOT NULL PRIMARY KEY, "approved_at" timestamp with time zone NOT NULL, "digest" varchar(64) NOT NULL, "revision" bigint NOT NULL CHECK ("revision" >= 0), "actor_id" uuid NOT NULL, "interpretation_id" uuid NOT NULL, "text_version_id" uuid NOT NULL);
--
-- Create model ThesisRecord
--
CREATE TABLE "macro_theses" ("id" uuid NOT NULL PRIMARY KEY, "revision" bigint NOT NULL CHECK ("revision" >= 0), "created_at" timestamp with time zone NOT NULL, "changed_at" timestamp with time zone NOT NULL, "current_approval_id" uuid NULL, "latest_interpretation_id" uuid NULL, "latest_text_id" uuid NULL, "owner_id" uuid NOT NULL);
--
-- Add field thesis to textversionrecord
--
ALTER TABLE "macro_thesis_text_versions" ADD COLUMN "thesis_id" uuid NOT NULL CONSTRAINT "macro_thesis_text_ve_thesis_id_2cd4212d_fk_macro_the" REFERENCES "macro_theses"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "macro_thesis_text_ve_thesis_id_2cd4212d_fk_macro_the" IMMEDIATE;
--
-- Add field thesis to interpretationrecord
--
ALTER TABLE "macro_thesis_interpretations" ADD COLUMN "thesis_id" uuid NOT NULL CONSTRAINT "macro_thesis_interpr_thesis_id_111c842e_fk_macro_the" REFERENCES "macro_theses"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "macro_thesis_interpr_thesis_id_111c842e_fk_macro_the" IMMEDIATE;
--
-- Create model CommandReceipt
--
CREATE TABLE "macro_thesis_command_receipts" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "command_id" uuid NOT NULL, "kind" varchar(16) NOT NULL, "request_digest" varchar(64) NOT NULL, "result" jsonb NOT NULL, "saved_at" timestamp with time zone NOT NULL, "owner_id" uuid NOT NULL, "thesis_id" uuid NOT NULL);
--
-- Create model AuditTransition
--
CREATE TABLE "macro_thesis_audit_transitions" ("sequence" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "kind" varchar(64) NOT NULL, "at" timestamp with time zone NOT NULL, "detail" jsonb NOT NULL, "thesis_id" uuid NOT NULL);
--
-- Add field thesis to approvalrecord
--
ALTER TABLE "macro_thesis_approvals" ADD COLUMN "thesis_id" uuid NOT NULL CONSTRAINT "macro_thesis_approvals_thesis_id_8ff5bf9d_fk_macro_theses_id" REFERENCES "macro_theses"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "macro_thesis_approvals_thesis_id_8ff5bf9d_fk_macro_theses_id" IMMEDIATE;
--
-- Create constraint macro_thesis_owner_target on model thesisrecord
--
ALTER TABLE "macro_theses" ADD CONSTRAINT "macro_thesis_owner_target" UNIQUE ("id", "owner_id");
--
-- Create constraint macro_thesis_revision_nonnegative on model thesisrecord
--
ALTER TABLE "macro_theses" ADD CONSTRAINT "macro_thesis_revision_nonnegative" CHECK ("revision" >= 0);
--
-- Create constraint macro_thesis_time_order on model thesisrecord
--
ALTER TABLE "macro_theses" ADD CONSTRAINT "macro_thesis_time_order" CHECK ("changed_at" >= ("created_at"));
--
-- Create constraint macro_thesis_draft_pair on model thesisrecord
--
ALTER TABLE "macro_theses" ADD CONSTRAINT "macro_thesis_draft_pair" CHECK ((("current_approval_id" IS NULL AND "latest_interpretation_id" IS NULL AND "latest_text_id" IS NULL) OR ("latest_interpretation_id" IS NOT NULL AND "latest_text_id" IS NOT NULL)));
--
-- Create constraint macro_text_scoped_target on model textversionrecord
--
ALTER TABLE "macro_thesis_text_versions" ADD CONSTRAINT "macro_text_scoped_target" UNIQUE ("thesis_id", "id");
--
-- Create constraint macro_text_named on model textversionrecord
--
ALTER TABLE "macro_thesis_text_versions" ADD CONSTRAINT "macro_text_named" CHECK ("exact_text"::text ~  E'\\S');
--
-- Create constraint macro_text_digest_sha256 on model textversionrecord
--
ALTER TABLE "macro_thesis_text_versions" ADD CONSTRAINT "macro_text_digest_sha256" CHECK ("text_digest"::text ~ '^[0-9a-f]{64}$');
--
-- Create constraint macro_text_parent_not_self on model textversionrecord
--
ALTER TABLE "macro_thesis_text_versions" ADD CONSTRAINT "macro_text_parent_not_self" CHECK (NOT ("parent_id" = ("id") AND "parent_id" IS NOT NULL));
--
-- Create constraint macro_interp_scoped_target on model interpretationrecord
--
ALTER TABLE "macro_thesis_interpretations" ADD CONSTRAINT "macro_interp_scoped_target" UNIQUE ("thesis_id", "id");
--
-- Create constraint macro_interp_text_target on model interpretationrecord
--
ALTER TABLE "macro_thesis_interpretations" ADD CONSTRAINT "macro_interp_text_target" UNIQUE ("thesis_id", "text_version_id", "id");
--
-- Create constraint macro_interp_digest_sha256 on model interpretationrecord
--
ALTER TABLE "macro_thesis_interpretations" ADD CONSTRAINT "macro_interp_digest_sha256" CHECK ("digest"::text ~ '^[0-9a-f]{64}$');
--
-- Create constraint macro_interp_origin_manual on model interpretationrecord
--
ALTER TABLE "macro_thesis_interpretations" ADD CONSTRAINT "macro_interp_origin_manual" CHECK ("origin" = 'user_supplied');
--
-- Create constraint macro_thesis_command_identity on model commandreceipt
--
ALTER TABLE "macro_thesis_command_receipts" ADD CONSTRAINT "macro_thesis_command_identity" UNIQUE ("owner_id", "command_id");
--
-- Create constraint macro_thesis_command_kind_allowed on model commandreceipt
--
ALTER TABLE "macro_thesis_command_receipts" ADD CONSTRAINT "macro_thesis_command_kind_allowed" CHECK ("kind" IN ('create', 'propose', 'approve'));
--
-- Create constraint macro_command_digest_sha256 on model commandreceipt
--
ALTER TABLE "macro_thesis_command_receipts" ADD CONSTRAINT "macro_command_digest_sha256" CHECK ("request_digest"::text ~ '^[0-9a-f]{64}$');
--
-- Create constraint macro_thesis_audit_kind_named on model audittransition
--
ALTER TABLE "macro_thesis_audit_transitions" ADD CONSTRAINT "macro_thesis_audit_kind_named" CHECK ("kind"::text ~  E'\\S');
--
-- Create constraint macro_approval_scoped_target on model approvalrecord
--
ALTER TABLE "macro_thesis_approvals" ADD CONSTRAINT "macro_approval_scoped_target" UNIQUE ("thesis_id", "id");
--
-- Create constraint macro_approval_revision_identity on model approvalrecord
--
ALTER TABLE "macro_thesis_approvals" ADD CONSTRAINT "macro_approval_revision_identity" UNIQUE ("thesis_id", "revision");
--
-- Create constraint macro_approval_digest_sha256 on model approvalrecord
--
ALTER TABLE "macro_thesis_approvals" ADD CONSTRAINT "macro_approval_digest_sha256" CHECK ("digest"::text ~ '^[0-9a-f]{64}$');
--
-- Create constraint macro_approval_revision_positive on model approvalrecord
--
ALTER TABLE "macro_thesis_approvals" ADD CONSTRAINT "macro_approval_revision_positive" CHECK ("revision" > 0);
--
-- Raw SQL operation
--

CREATE FUNCTION macro_thesis_reject_history_change() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'immutable thesis history: %', TG_TABLE_NAME USING ERRCODE = '23514';
END;
$$;

CREATE FUNCTION macro_thesis_guard_identity_and_progress() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'durable thesis cannot be deleted' USING ERRCODE = '23514';
    END IF;
    IF ROW(NEW.id, NEW.owner_id, NEW.created_at)
       IS DISTINCT FROM ROW(OLD.id, OLD.owner_id, OLD.created_at) THEN
        RAISE EXCEPTION 'thesis identity, owner, and creation time are immutable'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.revision < OLD.revision THEN
        RAISE EXCEPTION 'thesis revision cannot move backwards' USING ERRCODE = '23514';
    END IF;
    IF NEW.changed_at < OLD.changed_at THEN
        RAISE EXCEPTION 'thesis changed_at cannot move backwards' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER macro_thesis_identity_progress_guard
BEFORE UPDATE OR DELETE ON macro_theses
FOR EACH ROW EXECUTE FUNCTION macro_thesis_guard_identity_and_progress();

CREATE FUNCTION macro_thesis_is_string_array(value jsonb) RETURNS boolean
LANGUAGE sql IMMUTABLE STRICT AS $$
    SELECT CASE WHEN jsonb_typeof(value) = 'array' THEN
        NOT EXISTS (
            SELECT 1 FROM jsonb_array_elements(value) AS entries(element)
            WHERE jsonb_typeof(element) <> 'string'
        )
    ELSE FALSE END;
$$;
ALTER TABLE macro_thesis_interpretations ADD CONSTRAINT macro_interp_drivers_strings
    CHECK (macro_thesis_is_string_array(drivers));
ALTER TABLE macro_thesis_interpretations ADD CONSTRAINT macro_interp_signposts_strings
    CHECK (macro_thesis_is_string_array(invalidation_signposts));
ALTER TABLE macro_thesis_command_receipts ADD CONSTRAINT macro_command_result_object
    CHECK (jsonb_typeof(result) = 'object');
ALTER TABLE macro_thesis_audit_transitions ADD CONSTRAINT macro_thesis_audit_detail_object
    CHECK (jsonb_typeof(detail) = 'object');

CREATE TRIGGER macro_thesis_text_versions_immutable BEFORE UPDATE OR DELETE ON macro_thesis_text_versions
FOR EACH ROW EXECUTE FUNCTION macro_thesis_reject_history_change();

CREATE TRIGGER macro_thesis_interpretations_immutable BEFORE UPDATE OR DELETE ON macro_thesis_interpretations
FOR EACH ROW EXECUTE FUNCTION macro_thesis_reject_history_change();

CREATE TRIGGER macro_thesis_approvals_immutable BEFORE UPDATE OR DELETE ON macro_thesis_approvals
FOR EACH ROW EXECUTE FUNCTION macro_thesis_reject_history_change();

CREATE TRIGGER macro_thesis_command_receipts_immutable BEFORE UPDATE OR DELETE ON macro_thesis_command_receipts
FOR EACH ROW EXECUTE FUNCTION macro_thesis_reject_history_change();

CREATE TRIGGER macro_thesis_audit_transitions_immutable BEFORE UPDATE OR DELETE ON macro_thesis_audit_transitions
FOR EACH ROW EXECUTE FUNCTION macro_thesis_reject_history_change();

ALTER TABLE macro_thesis_text_versions ADD CONSTRAINT macro_text_parent_scope_fk FOREIGN KEY (thesis_id, parent_id)
REFERENCES macro_thesis_text_versions (thesis_id, id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE macro_thesis_interpretations ADD CONSTRAINT macro_interp_text_scope_fk FOREIGN KEY (thesis_id, text_version_id)
REFERENCES macro_thesis_text_versions (thesis_id, id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE macro_thesis_approvals ADD CONSTRAINT macro_approval_text_scope_fk FOREIGN KEY (thesis_id, text_version_id)
REFERENCES macro_thesis_text_versions (thesis_id, id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE macro_thesis_approvals ADD CONSTRAINT macro_approval_interp_text_fk FOREIGN KEY (thesis_id, text_version_id, interpretation_id)
REFERENCES macro_thesis_interpretations (thesis_id, text_version_id, id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE macro_thesis_approvals ADD CONSTRAINT macro_approval_owner_scope_fk FOREIGN KEY (thesis_id, actor_id)
REFERENCES macro_theses (id, owner_id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE macro_thesis_command_receipts ADD CONSTRAINT macro_command_owner_scope_fk FOREIGN KEY (thesis_id, owner_id)
REFERENCES macro_theses (id, owner_id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE macro_theses ADD CONSTRAINT macro_latest_text_scope_fk FOREIGN KEY (id, latest_text_id)
REFERENCES macro_thesis_text_versions (thesis_id, id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE macro_theses ADD CONSTRAINT macro_latest_interp_scope_fk FOREIGN KEY (id, latest_interpretation_id)
REFERENCES macro_thesis_interpretations (thesis_id, id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE macro_theses ADD CONSTRAINT macro_latest_draft_text_interp_fk FOREIGN KEY (id, latest_text_id, latest_interpretation_id)
REFERENCES macro_thesis_interpretations (thesis_id, text_version_id, id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE macro_theses ADD CONSTRAINT macro_current_approval_scope_fk FOREIGN KEY (id, current_approval_id)
REFERENCES macro_thesis_approvals (thesis_id, id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "macro_thesis_text_versions" ADD CONSTRAINT "macro_thesis_text_ve_parent_id_006fd243_fk_macro_the" FOREIGN KEY ("parent_id") REFERENCES "macro_thesis_text_versions" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "macro_thesis_text_versions_parent_id_006fd243" ON "macro_thesis_text_versions" ("parent_id");
ALTER TABLE "macro_thesis_interpretations" ADD CONSTRAINT "macro_thesis_interpr_text_version_id_41ca120b_fk_macro_the" FOREIGN KEY ("text_version_id") REFERENCES "macro_thesis_text_versions" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "macro_thesis_interpretations_text_version_id_41ca120b" ON "macro_thesis_interpretations" ("text_version_id");
ALTER TABLE "macro_thesis_approvals" ADD CONSTRAINT "macro_thesis_approvals_actor_id_f29453d4_fk_macro_web_user_id" FOREIGN KEY ("actor_id") REFERENCES "macro_web_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "macro_thesis_approvals" ADD CONSTRAINT "macro_thesis_approva_interpretation_id_429ea9ca_fk_macro_the" FOREIGN KEY ("interpretation_id") REFERENCES "macro_thesis_interpretations" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "macro_thesis_approvals" ADD CONSTRAINT "macro_thesis_approva_text_version_id_fc162bbc_fk_macro_the" FOREIGN KEY ("text_version_id") REFERENCES "macro_thesis_text_versions" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "macro_thesis_approvals_actor_id_f29453d4" ON "macro_thesis_approvals" ("actor_id");
CREATE INDEX "macro_thesis_approvals_interpretation_id_429ea9ca" ON "macro_thesis_approvals" ("interpretation_id");
CREATE INDEX "macro_thesis_approvals_text_version_id_fc162bbc" ON "macro_thesis_approvals" ("text_version_id");
ALTER TABLE "macro_theses" ADD CONSTRAINT "macro_theses_current_approval_id_2bad8097_fk_macro_the" FOREIGN KEY ("current_approval_id") REFERENCES "macro_thesis_approvals" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "macro_theses" ADD CONSTRAINT "macro_theses_latest_interpretatio_04faf8f4_fk_macro_the" FOREIGN KEY ("latest_interpretation_id") REFERENCES "macro_thesis_interpretations" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "macro_theses" ADD CONSTRAINT "macro_theses_latest_text_id_7c3388ad_fk_macro_the" FOREIGN KEY ("latest_text_id") REFERENCES "macro_thesis_text_versions" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "macro_theses" ADD CONSTRAINT "macro_theses_owner_id_fb105a4b_fk_macro_web_user_id" FOREIGN KEY ("owner_id") REFERENCES "macro_web_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "macro_theses_current_approval_id_2bad8097" ON "macro_theses" ("current_approval_id");
CREATE INDEX "macro_theses_latest_interpretation_id_04faf8f4" ON "macro_theses" ("latest_interpretation_id");
CREATE INDEX "macro_theses_latest_text_id_7c3388ad" ON "macro_theses" ("latest_text_id");
CREATE INDEX "macro_theses_owner_id_fb105a4b" ON "macro_theses" ("owner_id");
CREATE INDEX "macro_thesis_text_versions_thesis_id_2cd4212d" ON "macro_thesis_text_versions" ("thesis_id");
CREATE INDEX "macro_thesis_interpretations_thesis_id_111c842e" ON "macro_thesis_interpretations" ("thesis_id");
ALTER TABLE "macro_thesis_command_receipts" ADD CONSTRAINT "macro_thesis_command_owner_id_f95c0478_fk_macro_web" FOREIGN KEY ("owner_id") REFERENCES "macro_web_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "macro_thesis_command_receipts" ADD CONSTRAINT "macro_thesis_command_thesis_id_51d3c870_fk_macro_the" FOREIGN KEY ("thesis_id") REFERENCES "macro_theses" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "macro_thesis_command_receipts_owner_id_f95c0478" ON "macro_thesis_command_receipts" ("owner_id");
CREATE INDEX "macro_thesis_command_receipts_thesis_id_51d3c870" ON "macro_thesis_command_receipts" ("thesis_id");
ALTER TABLE "macro_thesis_audit_transitions" ADD CONSTRAINT "macro_thesis_audit_t_thesis_id_b5dff2a8_fk_macro_the" FOREIGN KEY ("thesis_id") REFERENCES "macro_theses" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "macro_thesis_audit_transitions_thesis_id_b5dff2a8" ON "macro_thesis_audit_transitions" ("thesis_id");
CREATE INDEX "macro_thesis_approvals_thesis_id_8ff5bf9d" ON "macro_thesis_approvals" ("thesis_id");
COMMIT;
